Implemented unique_ptr
coders-school/memory-management pull request #10
Opened 2020-09-13 19:30 UTC by J-Cieplinski

2020-09-15 11:48 UTC, jakjan95 approved these changes
Good Code :) Try to add delete statement for copy assignment  and it will be perfect :)

2020-09-20 07:26 UTC, ziobron requested changes
Probably there may be a memory leak in one case. Please check it.

2020-09-20 07:26 UTC, ziobron commented on .github/workflows/unique_ptr.yaml
> +  unique_ptr:
an additional job with valgrind would prove that there are no memory leaks

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +TEST_F(TestingPtr, ShouldProperlyDereference) {
properly is a forbidden word in test names ;)

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +}
this test is testing something else. It checks if you can use `get()` twice with the same result. 
It shoudn't work for `release()` function.

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ptr.reset(new std::string(valueToResetTo));
what about reset without an argument? :)
`ptr.reset()`

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(testString, *testPointer);
you should also check what happens to ptr after std::move

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(testString, *testPointer);
here as well, check what happens to ptr

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    cs::unique_ptr<std::string> testPointer(nullptr);
can I initialize cs::unique_ptr with default constructor here?
```suggestion
    cs::unique_ptr<std::string> testPointer{};
```

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(nullptr, ptr.get());
ok, here you have checked what happened to the source pointer. It should be integrated into one test in my opinion.

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    ptr_ = previousOwner.release();
what will happen it the target pointer already manages an object? I guess it's a memory leak. Please add a proper test case.

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    if (ptr_) {
`if` not needed. calling delete on nullptr is safe.

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    }
```suggestion
    delete ptr_;
    ptr_ = newPtr;
```

2020-09-20 07:26 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T* newPtr);
```suggestion
    void reset(T* newPtr = nullptr);
```
Default parameter would be useful

2020-09-20 08:01 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(testString, *testPointer);
Already done in different test `MovedPointerShouldBeNullptr`

2020-09-20 08:03 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(testString, *testPointer);
Added `MovedAssignedPointerShouldBeNullptr`

2020-09-20 08:04 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(nullptr, ptr.get());
Oh well, here I go reverting changes :D

2020-09-20 08:08 UTC, J-Cieplinski commented on homework/unique_ptr/unique_ptr.hpp
> +    ptr_ = previousOwner.release();
Well, it shouldn't, it's a constructor :D

2020-09-20 08:25 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    cs::unique_ptr<std::string> testPointer(nullptr);
After commit, yes

2020-09-20 08:45 UTC, J-Cieplinski commented on .github/workflows/unique_ptr.yaml
> +  unique_ptr:
done

2020-09-20 08:47 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +}
Done, i think?

2020-09-20 08:47 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +TEST_F(TestingPtr, ShouldProperlyDereference) {
Done

2020-09-20 08:47 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    ptr.reset(new std::string(valueToResetTo));
Done

2020-09-20 08:48 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(testString, *testPointer);
merged tests

2020-09-20 08:48 UTC, J-Cieplinski commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(testString, *testPointer);
Done

2020-09-20 08:49 UTC, J-Cieplinski commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T* newPtr);
I've done it differently now

2020-09-20 20:06 UTC, ziobron approved these changes

2020-09-20 20:07 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-20 20:07 UTC, closed without merging