unique_ptr
coders-school/memory-management pull request #11
Opened 2020-09-14 21:32 UTC by majkel84

own class unique_ptr with tests

2020-09-15 07:42 UTC, anraf1001 reviewed
Some comments

2020-09-15 07:42 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +    return ptr_;
If ptr is `nullptr` then returning it gives us `nullptr`. No need to make such if statements

2020-09-15 07:42 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +    return ptr_;
Same thing

2020-09-15 07:42 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +}
Memory leak. You need to delete ptr_ (if it's not nullptr) before `ptr_ = newPtr;`

2020-09-15 07:42 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +}
What if `ptr_` is `nullptr`?

2020-09-15 07:42 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(uPtr.get(), nullptr);
You need to delete ptr. uPtr won't automatically delete the object because after release it's not the owner

2020-09-15 11:52 UTC, jakjan95 reviewed
Code looks good, try to add delete statement for copy assignment :)

2020-09-15 11:52 UTC, jakjan95 commented on homework/unique_ptr/unique_ptr.hpp
> +}
+1

2020-09-15 11:52 UTC, jakjan95 commented on homework/unique_ptr/unique_ptr.hpp
> +}
We can delete nullptr so in my opinion this if condition is not needed :)

2020-09-15 19:04 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +    return ptr_;
done

2020-09-15 19:07 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +}
done

2020-09-15 19:12 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +}
done

2020-09-15 19:15 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +}
done

2020-09-16 08:56 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +    return ptr_;
done

2020-09-16 08:56 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(uPtr.get(), nullptr);
done

2020-09-19 12:57 UTC, MaciejSalamonski approved these changes
Nice work!

2020-09-19 12:57 UTC, MaciejSalamonski commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(uPtr.get(), nullptr);
@anraf1001 +1

2020-09-20 07:45 UTC, ziobron requested changes

2020-09-20 07:45 UTC, ziobron commented on .github/workflows/main.yml
> +  ctest:
additional job with valgrind would be useful

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*uPtr, 10);
```suggestion
    ASSERT_EQ(*uPtr, testValueOne);
```

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*uPtr3, 20);
```suggestion
    ASSERT_EQ(*uPtr3, testValueTwo);
```

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(uPtr.get(), nullptr);
not done? I don't see a delete here in this test

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +}
What about reset without an argument?
`uPtr.reset();`

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
To satisfy rule of 5 we also need copy and move assignment operators

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T* newPtr);
```suggestion
    void reset(T* newPtr = nullptr);
```
default argument would be useful

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +        ptr_ = otherPtr.release();
possible memory leak here when moving to the object that already holds something.

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    }
this `if` is not needed. just `return ptr_` will do completely the same thing.

2020-09-20 07:45 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    }
`if` not needed. deleting a nullptr is safe.

2020-09-20 19:05 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*uPtr, 10);
done

2020-09-20 19:05 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*uPtr3, 20);
done

2020-09-20 19:14 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +}
done

2020-09-20 19:27 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
done

2020-09-20 19:28 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T* newPtr);
done

2020-09-20 19:28 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +    }
done

2020-09-20 19:30 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +    }
done

2020-09-20 19:49 UTC, majkel84 commented on .github/workflows/main.yml
> +  ctest:
done

2020-09-20 20:11 UTC, ziobron requested changes

2020-09-20 20:11 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    delete ptr;
this is not correct. Only after `release()` you should delete memory.

2020-09-20 20:11 UTC, ziobron commented on .github/workflows/main.yml
> +    run: sudo apt-get update && sudo apt-get install valgrind
this line should be indented with 2 spaces more. The same for other below lines without dashes.

2020-09-20 20:30 UTC, majkel84 commented on .github/workflows/main.yml
> +    run: sudo apt-get update && sudo apt-get install valgrind
done

2020-09-20 20:41 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    delete ptr;
done

2020-09-20 20:42 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(uPtr.get(), nullptr);
done

2020-09-20 21:04 UTC, majkel84 commented on homework/unique_ptr/unique_ptr.hpp
> +        ptr_ = otherPtr.release();
can't release ptr_ so need a little hint here :)

2020-09-20 21:50 UTC, ziobron requested changes

2020-09-20 21:50 UTC, ziobron commented on .github/workflows/main.yml
> +      run: ctest -V
ctest -V doesn't work, because there are no proper commands in CMakeLists.txt.
however, under valgrind test are run properly.

2020-09-20 21:50 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    delete ptr;
But not exactly this way. release() returns you a raw pointer. You should assign a result of it to a pointer and delete it. Here you use pointer from get() function

2020-09-20 21:50 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*uPtr3, testValueTwo);
check also uPtr2 here

2020-09-20 21:50 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +        ptr_ = otherPtr.release();
yes, it's my bad. doing this via operaotr= is correct.

2020-09-21 17:44 UTC, WBigaj reviewed
I have checked your code and have nothing to add.

2020-09-21 20:02 UTC, majkel84 commented on .github/workflows/main.yml
> +      run: ctest -V
done

2020-09-21 20:22 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*uPtr3, testValueTwo);
done

2020-09-21 20:27 UTC, majkel84 commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    delete ptr;
ok so get just for test, and then realease from uPtr to a ptr and than delete it, so now it should be done :)

2020-09-22 12:28 UTC, ziobron approved these changes

2020-09-22 12:28 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
>      ASSERT_EQ(*uPtr3, testValueTwo);
```suggestion
    ASSERT_EQ(*uPtr3, testValueTwo);
    ASSERT_EQ(uPtr2.get(), nullptr);
```

2020-09-22 12:28 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    delete ptr;
In fact you don't need .get() in this test. release() return you the same pointer, so you could check it like this:
```cpp
    ptr = uPtr.release();
    ASSERT_EQ(*ptr, testValueOne);
    ASSERT_EQ(uPtr.get(), nullptr);      
    delete ptr;
```

2020-09-22 12:29 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-22 12:29 UTC, closed without merging