Checking if shared_ptr interface is fully implemented
coders-school/memory-management pull request #118
Opened 2022-03-29 13:25 UTC by anraf1001

2022-03-30 12:07 UTC, ziobron requested changes

2022-03-30 12:07 UTC, ziobron commented on tests/shared_ptr_interface_check.sh
> +check_regex $file 'shared_ptr\s*\(const shared_ptr& \w+\)' 'Copy constructor'
What if some put `shared_ptr(shared_ptr const &)`? or `shared_ptr(const shared_ptr & sth)`?
It may be easier to first apply a clang-format rules before running those checks. Otherwise we also need to handle all types of formatting here. What if someone is gonna put args in the next line?
```cpp
shared_ptr(
    shared_ptr const & item
);
```

2022-03-30 12:07 UTC, ziobron commented on tests/shared_ptr_interface_check.sh
> +check_regex $file 'shared_ptr\s*\(shared_ptr&& \w+\)' 'Move constructor'
What about `shared_ptr(shared_ptr &&item)`?

2022-03-31 04:20 UTC, ziobron requested changes

2022-03-31 04:20 UTC, ziobron commented on .github/workflows/main.yml
> +      run: bash ./shared_ptr_interface_check.sh
maybe just 
```suggestion
      run: ./shared_ptr_interface_check.sh
```

2022-03-31 04:20 UTC, ziobron commented on tests/shared_ptr_interface_check.sh
> +check_regex $file 'shared_ptr\s*\(\n?\s*?((const shared_ptr& \w+)|(shared_ptr const& \w+))\n?\s*?\)' 'Copy constructor'
Please add some tests showing which outputs are accepted and which are not. Take a look here: https://github.com/coders-school/git-checker/tree/main/.github/scripts, You can reuse some scripts or functions from there.
It would be good to have them split for each requirement (function like copy constructor, move constructor etc.) in a separate file.

2022-03-31 04:20 UTC, ziobron commented on tests/shared_ptr_interface_check.sh
> +#!/bin/bash
Please move it into .github/scripts

2022-04-03 04:48 UTC, ziobron requested changes

2022-04-03 04:48 UTC, ziobron commented on .github/scripts/shared_ptr_interface_check.sh
> +FILE=../../homework/shared_ptr/shared_ptr.hpp
I'm never 100% sure about using " in scripts, but I guess that it is safe to put paths in quotes.
```suggestion
FILE="../../homework/shared_ptr/shared_ptr.hpp"
```

2022-04-03 04:48 UTC, ziobron commented on .github/scripts/functions.sh
> +    grep -zoP "$2" $1 > /dev/null
why `-zoP`? What does it do? I don't even have it in `man grep`
Put `$1` in quotes as well.

2022-04-03 04:48 UTC, ziobron commented on .github/scripts/functions.sh
> +    PATTERN='shared_ptr\s*\(\n?\s*?((const shared_ptr)|(shared_ptr const))&[^&]*?\)'
Do not put spaces in regex for C++ code :) `\s+` is more generic and can behave properly if someone put an additional space.
`\s` already contain `\n`, there is no need to have it in a regex. 
`*?` doesn't make sense. `*` means any number, including 0.
```suggestion
    PATTERN='shared_ptr\s*\(\s*((const\s+shared_ptr)|(shared_ptr\s+const))\s*&.*\)'
```
Please check if my changes still pass the tests.
You can test your regex using https://regex101.com

2022-04-03 04:48 UTC, ziobron commented on .github/scripts/tests.sh
> +                                     const shared_ptr& other)")
what about 
`shared_ptr(shared_ptr const &sth)`
`shared_ptr(shared_ptr const & sth)`
`shared_ptr(const shared_ptr &sth)`
`shared_ptr(const shared_ptr & sth)`

I know that clang-format can unify that, but probably it's a really small change in regex. Thanks to that we can be more independent from clang-format.
Please also add such cases. I hope that my modification of regex can make it work.

2022-04-03 04:48 UTC, ziobron commented on .github/scripts/tests.sh
> +        echo $el | check_shared_ptr_copy_constructor /dev/stdin > /dev/null
why not 
```suggestion
        check_shared_ptr_copy_constructor "$el" > /dev/null
```

2022-04-03 04:48 UTC, ziobron commented on .github/scripts/tests.sh
> +}
There is a lot of code duplication here. Extract common parts to function.
I can see 3 variables here - `right_patterns`, `wrong_patterns`, `check_function`

2022-04-03 20:10 UTC, anraf1001 commented on .github/scripts/tests.sh
> +        echo $el | check_shared_ptr_copy_constructor /dev/stdin > /dev/null
`egrep` needs a file path as parameter, not a string. I don't have an idea how to make it clearer without making interface checking function more complicated (e.g. passing content of file to `check_regex` function and then piping it into `egrep`)

2022-04-10 06:10 UTC, ziobron requested changes

2022-04-10 06:10 UTC, ziobron commented on .github/scripts/tests.sh
> +    fi
why not `ret = $?` without if?

2022-04-10 06:10 UTC, ziobron commented on .github/scripts/tests.sh
>      return 0
You can move this common section to `run_tests`. Just pass an additional string to display which check passed or not.

2022-04-10 06:10 UTC, ziobron commented on .github/scripts/tests.sh
> +                                      "T operator*()")
I would like to see a test with different type name and additional spaces like 
`MyType & operator *()`
`N &operator* ()`
It should go to all template methods.

2022-04-10 06:10 UTC, ziobron commented on .github/scripts/tests.sh
> +    local wrong_use_count=("size_t use_count(shared_ptr ptr)")
what about
`int use_count()`
?

2022-04-10 06:12 UTC, ziobron commented on .github/scripts/tests.sh
> +        echo $el | check_shared_ptr_copy_constructor /dev/stdin > /dev/null
ok, it can stay like that.

2022-04-10 09:35 UTC, anraf1001 commented on .github/scripts/tests.sh
> +    fi
Then `wrong_cases`'s exit code will override `right_cases`'s one.
I can see 2 options to avoid that if statement:
1. Just adding `$?` to `ret` without caring if `ret` equals 1 or 2
2. Using bitwise or (`ret=$(( $ret | 1 ))`) if we need only 2 values of exit (0 and 1)

2022-04-24 10:32 UTC, ziobron requested changes

2022-04-24 10:32 UTC, ziobron commented on .github/scripts/tests.sh
> +function check_right_cases() {
can you add comments with the description of function parameters?

2022-04-24 10:32 UTC, ziobron commented on .github/scripts/tests.sh
> +        if [[ $? -eq 0 ]]; then
in line 11 there is `!=`. Here we have `-eq`. Please use only one uniform way.

2022-04-24 10:32 UTC, ziobron commented on .github/scripts/tests.sh
> +    fi
Maybe just sum the return values. If we have 0 then everything is fine. Anything else means that there was an error.

2022-04-24 10:32 UTC, ziobron commented on .github/scripts/tests.sh
> +    return $?
can we merge those 2 lines?

```suggestion
    return run_test "copy ctor" check_shared_ptr_copy_constructor right_copy_ctors[@] wrong_copy_ctors[@]
```

or the behavior is different then?

2022-04-24 10:32 UTC, ziobron commented on .github/scripts/tests.sh
> +                                "N *operator-> ()")
Are all of these cases problematic, or can we only comment out specific lines here, if some of them are ok?

2022-04-24 18:54 UTC, anraf1001 commented on .github/scripts/tests.sh
> +    return $?
As far as I know, `return` in bash can only return exit codes, which can only be accessed using `$?`. Suggested version won't work at all.

2022-04-27 16:25 UTC, ziobron requested changes
Recently I have refreshed my knowlege on good pracices regarding commit messages. Please read and stick to this doc -https://reflectoring.io/meaningful-commit-messages/
I know that my previous commits does not stick to it, but now I also use these rules :)

2022-04-27 16:25 UTC, ziobron commented on .github/scripts/tests.sh
> +
This code with repetitions of summing up return value looks ugly :)
Can you just use a global variable like `error_count` that is incremented in `run_test()` or `check_wrong_cases ()` or `check_right_cases()` functions and simply return it here?
In scripts, it is not a big deal to use global variables as they usually have the scope of one line and are not compiled from multiple source files.

2022-04-27 16:25 UTC, ziobron commented on .github/workflows/main.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
This should be a separate PR. It has nothing in common with checking if the shared_ptr interface is fully implemented. Please raise a new one with this change.

2022-04-27 18:51 UTC, ziobron approved these changes

2022-04-27 18:52 UTC, merged

2022-04-27 18:52 UTC, ziobron commented
Your PR was merged!
🏅 2 XP granted. Thanks @anraf1001 for making course materials better!