unique_ptr homework
coders-school/memory-management pull request #12
Opened 2020-09-15 11:40 UTC by jakjan95

Author @jakjan95

2020-09-19 13:00 UTC, MaciejSalamonski approved these changes
Very nice code @jakjan95  :)

2020-09-19 13:00 UTC, MaciejSalamonski commented on homework/unique_ptr/include/UniquePtr.hpp
> +        throw NullptrDereferenceError();
+1 for throwing an exception

2020-09-20 08:02 UTC, ziobron requested changes
There is no test for arrow operator.

2020-09-20 08:02 UTC, ziobron commented on homework/unique_ptr/tests/UniquePtr.ut.cpp
> +}
you should check what happens to source pointers in move operations

2020-09-21 07:48 UTC, jakjan95 commented
Tests added, stuff mentioned by Lukasz fixed :)

2020-09-21 10:29 UTC, ziobron approved these changes

2020-09-21 10:29 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-21 10:29 UTC, closed without merging