unique_ptr homework
coders-school/memory-management pull request #14
Opened 2020-09-15 20:08 UTC by Kuba-Wi

2020-09-16 09:55 UTC, anraf1001 reviewed
Some comments

2020-09-16 09:55 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
You should delete copy constructor to disable copying unique_ptrs

2020-09-16 09:55 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +        pointer_ = nullptr;
You don't have to make `pointer_` nullptr. After dtor execution that whole object will be removed from memory.

2020-09-17 18:48 UTC, Kuba-Wi commented on homework/unique_ptr/unique_ptr.hpp
> +        pointer_ = nullptr;
It's better to set nullptr because later it is easier to check if this pointer points on something.

2020-09-17 18:48 UTC, Kuba-Wi commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
Actually they move pointer and don't copy.

2020-09-17 19:33 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +        pointer_ = nullptr;
But we are talking about destructor. That whole object won't exist "in a second".

2020-09-17 19:36 UTC, anraf1001 commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
Ok I haven't seen that you've created copy and move constructor that do exactly the same thing. I still think that you should delete copy constructor instead of making it pseudo move ctor but this's is only my point of view.

2020-09-19 13:05 UTC, MaciejSalamonski approved these changes
good job  👍

2020-09-19 13:05 UTC, MaciejSalamonski commented on homework/unique_ptr/unique_ptr.hpp
> +        pointer_ = nullptr;
I agree with anraf

https://stackoverflow.com/questions/3116980/do-i-have-to-set-pointer-to-nullptr-in-destructor

2020-09-20 08:19 UTC, ziobron requested changes
Use constexpr for magic values.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/.github/module3.yml
> +  unique_ptr:
Please add a valgrind / sanitizer job to prove that there are no memory leaks

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_TRUE(ptr->size() == 4);
4 is a magic value. Avoid it.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_TRUE(*ptr.get() == 42);
Use ASSERT_EQ / ASSERT_NE

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_TRUE(main_ptr.get() != nullptr);
Copy operations should be prohibited.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +}
you should also delete ptr here.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    }
just
```suggestion
    delete pointer_;
```
It's safe to delete nullptr.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
@anraf1001 is right. Now you have created an auto_ptr which is very easy to use incorrectly. For example getting an element from vector (via operator[]) will invalidate the element in collection. Definitely disable the usage of copy operations

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    ~unique_ptr();
You should also have a move and copy assignment operators.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T* new_ptr);
```suggestion
    void reset(T* new_ptr = nullptr);
```
The default value will be useful here

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    }
`if` not needed.
Just `delete pointer_;`
Deleting nullptr is safe.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    if(pointer_ != nullptr) {
if not needed.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +}
prohibit using a copy constructor by = delete;
This behaviour is incorrect.

2020-09-20 08:19 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +
there are no tests for move operation

2020-09-21 17:45 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-09-22 18:14 UTC, ziobron approved these changes

2020-09-22 18:14 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_TRUE(*main_ptr == 42);
42 is a magic value. Name it and reuse it.

2020-09-22 18:14 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_TRUE(*main_ptr == 42);
Instead of ASSERT_TRUE you should use ASSERT_EQ and ASSERT_NE

2020-09-22 18:14 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    T* pointer_;
```suggestion
    T* pointer_ = nullptr;
```
The previous version was better.

2020-09-22 18:15 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-22 18:15 UTC, closed without merging