Working (probably)
coders-school/memory-management pull request #15
Opened 2020-09-15 21:57 UTC by kuchichan

Ready to review.

2020-09-17 11:42 UTC, jakjan95 reviewed
Code looks good, just add nullptr handling and delete assignment copy operator(=) :)

2020-09-17 11:42 UTC, jakjan95 commented on homework/unique_ptr/UniquePtr.hpp
> +}
Remember about nullptr

2020-09-19 13:07 UTC, MaciejSalamonski approved these changes
Nice work :~}. Have a good day ;p

2020-09-19 13:07 UTC, MaciejSalamonski commented on homework/unique_ptr/UniquePtr.hpp
> +}
+1

2020-09-20 08:39 UTC, ziobron requested changes

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME}-ut PRIVATE gtest_main lib -fsanitize=undefined)
I don't know if sanitizing for undefined behaviour covers all cases with memory. Maybe try with -fsanitize=address

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    ASSERT_EQ(200, *ptr);
magic value

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    ASSERT_EQ(*hello_3, 10);
what about `ptr` after move?

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
You should add more test cases for moving to UniquePtr that already manages the object, for get function and for arrow operator.

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +        if (ptr_)
if not needed.

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    UniquePtr<T>& operator=(UniquePtr&& ptr) noexcept;
you are missing a copy assignment operator

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    T operator*() const;
operator* should return a reference, not a copy

2020-09-20 08:39 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    if (ptr_) {
if not needed.

2020-09-21 13:10 UTC, kuchichan commented on homework/unique_ptr/CMakeLists.txt
> +target_link_libraries(${PROJECT_NAME}-ut PRIVATE gtest_main lib -fsanitize=undefined)
Done.

2020-09-21 13:11 UTC, kuchichan commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    ASSERT_EQ(200, *ptr);
Repaired.

2020-09-21 13:11 UTC, kuchichan commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    ASSERT_EQ(*hello_3, 10);
Additional Assertion was introduced.

2020-09-21 13:11 UTC, kuchichan commented on homework/unique_ptr/UniquePtr.hpp
> +        if (ptr_)
Done.

2020-09-21 13:12 UTC, kuchichan commented on homework/unique_ptr/UniquePtr.hpp
> +    UniquePtr<T>& operator=(UniquePtr&& ptr) noexcept;
Done.

2020-09-21 13:12 UTC, kuchichan commented on homework/unique_ptr/UniquePtr.hpp
> +    T operator*() const;
Done.

2020-09-21 13:12 UTC, kuchichan commented on homework/unique_ptr/UniquePtr.hpp
> +    if (ptr_) {
If removed.

2020-09-21 13:13 UTC, kuchichan commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
Additional testcase has been added.

2020-09-21 17:47 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-09-22 13:38 UTC, ziobron requested changes

2020-09-22 13:38 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
>      ptr.reset(new int(200));
```suggestion
    ptr.reset(new int(expectedValue));
```

2020-09-22 13:38 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +        UniquePtr<std::pair<size_t, size_t>>(new std::pair<size_t, size_t>(10, 20));
```suggestion
        UniquePtr<std::pair<size_t, size_t>>(new std::pair<size_t, size_t>{expectedValue});
```

2020-09-22 13:38 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    UniquePtr<T>& operator=(UniquePtr&& ptr) noexcept;
I still don't see copy assignment operator. The above is move assignment operator. Copy takes `const UniquePtr&` as an argument.

2020-09-22 14:56 UTC, kuchichan commented on homework/unique_ptr/UniquePtr.hpp
> +    UniquePtr<T>& operator=(UniquePtr&& ptr) noexcept;
I hope now its ok :). Sorry for that, because I have noticed, that is missed also move assignment operator.

2020-09-22 14:56 UTC, kuchichan commented on homework/unique_ptr/UniquePtr-ut.cpp
>      ptr.reset(new int(200));
Done.

2020-09-22 14:56 UTC, kuchichan commented on homework/unique_ptr/UniquePtr-ut.cpp
> +        UniquePtr<std::pair<size_t, size_t>>(new std::pair<size_t, size_t>(10, 20));
Done.

2020-09-22 18:18 UTC, ziobron requested changes
There is a memory leak in your solution. Try to catch it yourself. In case of problems just ask :)

2020-09-22 18:18 UTC, ziobron commented
https://github.com/kuchichan/memory-management/runs/1150065689?check_suite_focus=true

2020-09-22 18:59 UTC, kuchichan commented
Leak is fixed now.

2020-09-22 21:33 UTC, ziobron approved these changes

2020-09-22 21:33 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-22 21:33 UTC, closed without merging