Homework - UniquePtr
coders-school/memory-management pull request #16
Opened 2020-09-16 18:59 UTC by MonikaZelechowska

2020-09-17 11:45 UTC, jakjan95 approved these changes
Everything looks good! :)

2020-09-19 13:12 UTC, MaciejSalamonski reviewed
Hi! You have sent two implementations of unique_ptr. Which implementation should I check?

2020-09-20 09:32 UTC, ziobron requested changes
Nice solution :)
A few improvements will be useful

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
don't forget to `delete tempPtr;`

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
also a reset without an argument should be tested
`testPtr.reset();`

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
also moving to a pointer that already holds an object should be tested.

2020-09-20 09:32 UTC, ziobron commented on exercises/uniquPointer.cpp
> +#include <iostream>
I'm not checking this implementation because it's in another path.

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    void reset(T* newPtr);
```suggestion
    void reset(T* newPtr = nullptr);
```
default argument would be useful :)

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +        if (ptr_ != nullptr) {
this if is not necessary

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    }
If we use exceptions then you probably don't want to catch it here. It should propagate and it should be caught somewhere else, eg. in tests by ASSERT_THROW

2020-09-20 09:32 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    if (ptr_ != nullptr) {
if not necessary

2020-09-20 10:21 UTC, MonikaZelechowska commented on homework/unique_ptr/UniquePtr.hpp
> +    }
Thanks for advice. I used to use _try, catch _and_ throw_ in wrong way :)

2020-09-20 20:16 UTC, ziobron requested changes
Almost good :)
It would be good to see that it works on CI with 2 jobs - casual UTs and UTs under valgrind or compiled with ASAN. It would prove that everything works fine.

2020-09-20 20:16 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    delete tempPtr;
you should not call delete here. If reset does swap it will work, however, reset should only copy a source pointer and not modify it.

2020-09-20 20:16 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    delete tempPtr;
the same here - without delete.

2020-09-20 21:51 UTC, ziobron commented
The code looks good, but I still need a proof - a working CI with valgrind / ASAN :)

2020-09-21 17:49 UTC, WBigaj reviewed
Why have you sent two versions of program?

2020-10-14 09:58 UTC, ziobron approved these changes

2020-10-14 09:59 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-10-14 09:59 UTC, closed without merging