unique_ptr Homework
coders-school/memory-management pull request #17
Opened 2020-09-17 14:58 UTC by kari0036

2020-09-18 16:10 UTC, jakjan95 reviewed
Code looks good, just remember about copy and move assignments :)

2020-09-19 13:14 UTC, MaciejSalamonski approved these changes
Hi! Nice code! I aporove this pr 👍

2020-09-19 13:14 UTC, MaciejSalamonski commented on homework/unique_ptr/unique_ptr.hpp
> +}
I agree with @jakjan95  https://stackoverflow.com/questions/3116980/do-i-have-to-set-pointer-to-nullptr-in-destructor

2020-09-20 10:05 UTC, ziobron requested changes

2020-09-20 10:05 UTC, ziobron commented on .github/workflows/main.yml
> +  ctest:
add a job with valgrind / asan to prove that there are no memory leaks

2020-09-20 10:05 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +
good tests. There is only one thing missing - moving into a pointer that already manages another object

2020-09-20 10:05 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    ptr_ = otherPtr.release();
move it into constructor initializer list

2020-09-20 10:05 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    if (ptr_) {
if not needed. deleting a nullptr is safe.

2020-09-20 10:05 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +
you are missing move and copy assignment operators

2020-09-20 20:19 UTC, ziobron requested changes
Looks fine, but CI tells that:
 fatal error: catch.hpp: No such file or directory
29
    2 | #include "catch.hpp"

2020-09-21 17:51 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-09-22 13:41 UTC, ziobron requested changes
Another CI error
valgrind: ./uniquePtr-ut: No such file or directory
##[error]Process completed with exit code 127.

2020-09-22 18:21 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-22 18:21 UTC, closed without merging