Homework unique ptr
coders-school/memory-management pull request #18
Opened 2020-09-17 16:11 UTC by Vicx95

2020-09-18 08:12 UTC, anraf1001 reviewed
Some comments

2020-09-18 08:12 UTC, anraf1001 commented on homework/unique_ptr/CMakeLists.txt
> +# Download and unpack googletest at configure time
You should add `cmake_minimum_required(VERSION <ver. num>)`

2020-09-18 08:12 UTC, anraf1001 commented on homework/unique_ptr/UniquePtr.hpp
> +    return nullptr;
If this statement is true it means that `resource_` is nullptr. So you can simply return `resource_`.

2020-09-18 15:58 UTC, jakjan95 approved these changes
Code looks good, just correct stuff mentioned by @anraf1001 and it will be perfect :)

2020-09-19 11:58 UTC, anraf1001 approved these changes

2020-09-19 13:17 UTC, MaciejSalamonski approved these changes
i dont have any comments! Nice code~!

2020-09-20 10:34 UTC, ziobron requested changes

2020-09-20 10:34 UTC, ziobron commented on .github/workflows/module.yml
> +  UniquePtr:
add a valgrind / asan job to prove that there are no memory leaks

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    T operator*() const;
```suggestion
    T& operator*() const;
```
This operator should return a reference, not a copy

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    if (!resource_) {
This is not a valid behavior. If we have a nullptr we return *this.  You should check if it's identity assignment (a == a)

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    delete resource_;
we should not delete in release function. You return a dangling pointer from it. ❗️

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    if (resource_) {
if not needed. deleting a nullptr is safe.

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.ut.cpp
> +        UniquePtr<int> ptr{new int{9}};
There are many magic values in this file. Please fix them.

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.ut.cpp
> +}
there should be a memory leak. You need to assign a result of release() function to a pointer and delete it.

2020-09-20 10:34 UTC, ziobron commented on homework/unique_ptr/UniquePtr.ut.cpp
> +}
what about a reset without an argument?
`ptr.reset();`

2020-09-21 17:52 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-10-14 10:16 UTC, ziobron approved these changes

2020-10-14 10:17 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-10-14 10:17 UTC, closed without merging