Unique ptr
coders-school/memory-management pull request #19
Opened 2020-09-17 21:31 UTC by NeoBauer

2020-09-18 16:07 UTC, jakjan95 requested changes
Code need little improvement and it will be fine :)

2020-09-18 16:07 UTC, jakjan95 commented on homework/unique_ptr/uniqueptr.hpp
> +template <class T> class unique_ptr {
instead of class use typename in template

2020-09-18 16:07 UTC, jakjan95 commented on homework/unique_ptr/uniqueptr.hpp
> +
I would rather use that kind of naming convention: T* something, T& something :)

2020-09-18 16:07 UTC, jakjan95 commented on homework/unique_ptr/uniqueptr.hpp
> +  puts("Yes, we created uniqueptr! :)");
puts() is bad habit in C so i would not use it in C++

2020-09-18 16:07 UTC, jakjan95 commented on homework/unique_ptr/uniqueptr.hpp
> +  std::cout << "Destructor called where raw_ptr adress is: " << this->rawPtr_ << '\n';
cout can throw exception so it is not good idea to put it here

2020-09-18 16:07 UTC, jakjan95 commented on homework/unique_ptr/uniqueptr.hpp
> +template <class T> T &unique_ptr<T>::operator*() { return *rawPtr_; }
what about nullptr dereference?

2020-09-18 20:41 UTC, NeoBauer commented on homework/unique_ptr/uniqueptr.hpp
> +
> I would rather use that kind of naming convention: T* something, T& something :)

May I ask you for an example?

2020-09-19 13:29 UTC, MaciejSalamonski reviewed
Hi i have one question :P

2020-09-19 13:29 UTC, MaciejSalamonski commented on homework/unique_ptr/uniqueptr.hpp
> +  delete rawPtr_;
Could you explain that?

2020-09-19 16:43 UTC, NeoBauer commented on homework/unique_ptr/uniqueptr.hpp
> +  delete rawPtr_;
Where do you see the problem?

2020-09-20 10:40 UTC, ziobron requested changes
There are no unit tests. Without them you cannot prove that your code is correct. Please also add a job that run tests under valgrind or compile them with asan.

2020-09-20 20:27 UTC, ziobron requested changes

2020-09-20 20:27 UTC, ziobron commented on .github/workflows/UniquePtr.yml
> +          valgrind --leak-check=yes ./UniquePointerExe
run UTs under valgrind. Main executable is optional.

2020-09-20 20:27 UTC, ziobron commented on homework/unique_ptr/tests/tests.cpp
> +      firstUnique.reset(nullptr);
use empty reset call - `firstUnique.reset();`

2020-09-20 20:27 UTC, ziobron commented on homework/unique_ptr/tests/tests.cpp
> +}
tests for release() and some dereference cases are missing

2020-09-20 20:27 UTC, ziobron commented on homework/unique_ptr/uniqueptr.hpp
>    unique_ptr &operator=(const unique_ptr &) = delete; // copy assigment operator
what about move assignment operator? It's missing.

2020-09-20 20:27 UTC, ziobron commented on homework/unique_ptr/uniqueptr.hpp
>    T release();
release should return T*

2020-09-21 17:54 UTC, WBigaj reviewed
I have checked your code and there is some unremoved comments.

2020-09-21 17:54 UTC, WBigaj commented on homework/unique_ptr/main.cpp
> +// std::cout << "Data stored in firstUnique: " << (*firstUnique).data_ << '\n'; // dereferencing nullptr!
Is this comment needed?

2020-09-21 17:54 UTC, WBigaj commented on homework/unique_ptr/main.cpp
> +//PtrShop.push_back(firstUnique); // will not work, because copy constructor is deleted!
Is this comment needed?

2020-09-21 17:54 UTC, WBigaj commented on homework/unique_ptr/uniqueptr.hpp
> +                                 unique_ptr using .get()"); else  */
Is this comment needed?

2020-09-22 18:36 UTC, ziobron requested changes
There is one memory leak: https://github.com/NeoBauer/memory-management/runs/1151048352?check_suite_focus=true
Check valgrind output

2020-09-22 18:36 UTC, ziobron commented on homework/unique_ptr/tests/tests.cpp
> +      THEN("unique_ptr is nullptr") { REQUIRE(firstUnique.get() == nullptr); }
And we have a memory leak

2020-09-22 21:35 UTC, ziobron approved these changes
👍

2020-09-22 21:35 UTC, ziobron commented on homework/unique_ptr/tests/tests.cpp
> +      unique_ptr<TestClass> containerForReleased = firstUnique.release();
or just call delete explicitly on returned raw pointer

2020-09-22 21:36 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-22 21:36 UTC, closed without merging