unique_ptr homework
coders-school/memory-management pull request #21
Opened 2020-09-18 18:27 UTC by McKucia

2020-09-20 10:43 UTC, ziobron requested changes
There are no unit tests. Without them you cannot prove that you have a correct implementation. Also you need to run them under valgrind or compile them with asan.

2020-09-21 17:56 UTC, WBigaj reviewed
I have checked your code and have one question.

2020-09-21 17:56 UTC, WBigaj commented on module1/homework/unique_ptr.cpp
> +//    unique_ptr(T& ptr) : ptr_(&ptr) {};
What is this comment?

2020-10-14 10:21 UTC, ziobron requested changes
Looks good, but please add a CI job to prove that there are no memory leaks under valgrind. Remember to add running a valgrind job.

2020-10-14 10:21 UTC, ziobron commented on module1/homework/unique_ptr.hpp
> +    void reset(T* otherPtr){
reset can also be called without an argument. If you add a default argument value `T* otherPtr = nullptr` it will cover this case. ALso add a test for it.

2020-11-14 22:41 UTC, closed without merging