Homework - unique_ptr
coders-school/memory-management pull request #22
Opened 2020-09-18 20:05 UTC by mateusz-talma

2020-09-19 13:33 UTC, MaciejSalamonski approved these changes
Hi, nice code! Keep it up ;p

2020-09-19 13:33 UTC, MaciejSalamonski commented on homework/unique_ptr/UniquePtr.hpp
> +    if (ptr_) {
You dont have to check if ptr is nullptr (in this case)

https://stackoverflow.com/questions/3116980/do-i-have-to-set-pointer-to-nullptr-in-destructor

2020-09-20 10:49 UTC, ziobron requested changes

2020-09-20 10:49 UTC, ziobron commented on .github/workflows/uniquePtr.yml
> +  ctest:
add a valgrind / asan job as well to prove that you have no memory leaks.

2020-09-20 10:49 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
please also test a reset function without an argument
`doublePtr.reset();`

2020-09-20 10:49 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
nice, please also test moving to the pointer that already holds another object.

2020-09-20 10:49 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    T& operator=(const T&) = delete;
you are missing a move assignment operator

2020-09-20 10:49 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    void reset(T* newPtr);
```suggestion
    void reset(T* newPtr = nullptr);
```
the default argument is useful here

2020-09-20 10:49 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    if (ptr_) {
if not needed. deleting nullptr is safe.

2020-09-21 17:58 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-09-21 17:58 UTC, WBigaj commented on homework/unique_ptr/UniquePtr.hpp
> +    if (ptr_) {
As @MaciejSalamonski told deleting nullptr is safe.

2020-10-14 10:25 UTC, ziobron approved these changes

2020-10-14 10:26 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-10-14 10:26 UTC, closed without merging