Add implementation of Unique Pointer
coders-school/memory-management pull request #23
Opened 2020-09-19 17:36 UTC by Pawellos

Implementation own Unique_ptr (constructor, move constructor, destructor, operatos, methods: get, reset, release, removed copy constructor)

2020-09-20 09:34 UTC, MaciejSalamonski approved these changes
Hi nice code! Have a great day ;~}

2020-09-20 09:34 UTC, MaciejSalamonski commented on homework/unique_ptr/UniquePointer.hpp
> +    if (ptr_) {
I think that You don't have to check if ptr isn't null pointer in destructor

https://stackoverflow.com/questions/50569942/check-pointer-is-not-null-in-destructor

Delete or delete[] are defined for nullptr. They do nothing

2020-09-20 11:07 UTC, Pawellos commented on homework/unique_ptr/UniquePointer.hpp
> +    if (ptr_) {
Ok, thanks. I was not sure :)

2020-09-20 18:56 UTC, ziobron requested changes

2020-09-20 18:56 UTC, ziobron commented on homework/unique_ptr/UniquePointer.hpp
> +    T operator*() const;
```suggestion
    T& operator*() const;
```
This operator should return a reference, not a copy

2020-09-20 18:56 UTC, ziobron commented on homework/unique_ptr/UniquePointer.hpp
> +UniquePointer<T>::UniquePointer() {}
default constructor has uninitialized pointer, so it causes undefined behavior ❗️

2020-09-20 18:56 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(33, *ptr);
avoid magic values. Name them.

2020-09-20 18:56 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +}
there is a memory leak in this test case. You should assign a result of release() function to a pointer and delete it.

2020-09-20 18:56 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(20, *ptr);
What is 20? Why 20? Magic value.
What about uPtr after move? Also check if it's in a valid state.

2020-09-20 18:56 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    ASSERT_EQ(14, *ptr2);
what about ptr? you should also test it.

2020-09-20 18:57 UTC, ziobron commented
And it will be useful to have a CI job with valgrind / asan to prove that there are no memory leaks.

2020-09-21 18:00 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-09-24 19:57 UTC, ziobron commented
Ok, but please move homework/unique_ptr/.github/workflows/unique.yml to .github/workflows/unique.yml. It will trigger CI and I will be able to check results.

2020-09-25 13:05 UTC, Pawellos commented
> Ok, but please move homework/unique_ptr/.github/workflows/unique.yml to .github/workflows/unique.yml. It will trigger CI and I will be able to check results.

Ok, I think it's done  :)

2020-10-14 10:31 UTC, ziobron commented
Invalid workflow file
You have an error in your yaml syntax on line 7

Probably too many spaces in indentation. 4 instead of 2. Check it.

2020-10-14 10:32 UTC, ziobron commented on .github/workflows/unique.yml
> +      runs-on: ubuntu-20.04
```suggestion
    runs-on: ubuntu-20.04
```

2020-10-14 12:25 UTC, ziobron commented on .github/workflows/unique.yml
> +        valgrind ./test
no such file or directory ./test. How is your UT binary named?

2020-10-14 12:30 UTC, Pawellos commented on .github/workflows/unique.yml
> +        valgrind ./test
I am lost with this. I think it is test.cpp

2020-10-14 12:42 UTC, ziobron commented on .github/workflows/unique.yml
> +        valgrind ./test
You can get this from CMakeLists.txt

```cmake
project(unique_ptr)
 enable_testing()

 add_executable(${PROJECT_NAME} main.cpp)
 add_executable(${PROJECT_NAME}-ut test.cpp)
```

It is `${PROJECT_NAME}-ut`, so it's `unique_ptr-ut`

2020-10-14 12:53 UTC, Pawellos commented on .github/workflows/unique.yml
> +        valgrind ./test
Thanks ! I was messing with this a while and i was not sure what is wrong. Anyway thanks for help :)

2020-10-14 13:13 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-10-14 13:13 UTC, closed without merging