Unique ptr homework
coders-school/memory-management pull request #24
Opened 2020-09-19 22:01 UTC by niemarcin

2020-09-20 09:38 UTC, MaciejSalamonski approved these changes
Very nice code! Keep it up ;~} Have a great day!!

2020-09-20 09:38 UTC, MaciejSalamonski commented on homework/unique_ptr/unique_ptr.hpp
> +namespace coders {
+1

2020-09-20 09:38 UTC, MaciejSalamonski commented on homework/unique_ptr/unique_ptr.hpp
> +    if (rawPtr_) {
I think that You don't have to check if pointer is nullpointer in destructor

https://stackoverflow.com/questions/50569942/check-pointer-is-not-null-in-destructor

Delete and delete[] are defined for nullptr. They do nothing

2020-09-20 19:16 UTC, ziobron requested changes

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    auto releasedRawPtr = uniquePtr.release();
there is a memory leak. You should delete releasedRawPtr at the end of this test case.

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*ptr2, testValue);
you should also check ptr1 after move.

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(*ptr2, testValue);
check ptr1 as well

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(ptr1.get(), nullptr);
ok, here is this check. Merge it into one test case.

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    ASSERT_EQ(ptr1.get(), nullptr);
the same here :)

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +    uniquePtr.reset(new std::vector<int>{10, 11});
i'm missing a test case on reset without argument - `uniquePtr.reset();`

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr() = delete;
why don't we want to create a unique_ptr like this:
`unique_ptr<int> uptr {};` 
It's possible with std::unique_ptr.

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    if (oldPtr) {
if not necessary. It's safe to delete nullptr.

2020-09-20 19:16 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T* ptr) noexcept;
```suggestion
    void reset(T* ptr = nullptr) noexcept;
```
Default argument would be useful

2020-09-20 19:49 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    if (rawPtr_) {
https://en.cppreference.com/w/cpp/language/delete
"If expression evaluates to a null pointer value, no destructors are called, and the deallocation function may or may not be called (it's unspecified), but the default deallocation functions are guaranteed to do nothing when passed a null pointer."

Well, it's unspecified as mentioned above. In my case I have had errors of double deleted pointer unless checked if it had been nullptr.

2020-09-20 19:50 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    if (rawPtr_) {
Maybe I miss something...

2020-09-21 18:01 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-09-22 12:16 UTC, ziobron approved these changes

2020-09-22 12:17 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-09-22 12:17 UTC, closed without merging