Homework unique pointer
coders-school/memory-management pull request #26
Opened 2020-09-20 15:52 UTC by mariuszlisowski

Short code but a day spent to make it work according to guidelines. Simplified implementation - certainly with bugs. Tested in main source file - passes basic functionality. There is also a verbose version of the code in the 'verbose' folder which helps to understand what is what and contains many explanations.

2020-09-20 19:56 UTC, ziobron requested changes
Missing unit test, as you mentioned.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/main.cpp
> +    int* ptr = ptr5.release();
memory leak here. You should `delete ptr;` at the end of the program

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr(std::nullptr_t);
this overload is not needed. Nullptr will match T* version.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr(unique_ptr const&);
```suggestion
    unique_ptr(unique_ptr const&) = delete;
```
We don't want to have a copy constructor

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr& operator=(std::nullptr_t);
This one is strange. Assignment operator with nullptr. unique_ptr does not have it as far as I remember.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T*);
```suggestion
    void reset(T* = nullptr);
```
Default argument will be useful

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +}
No, copy constructor should be deleted. No implementation needed.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    delete rhs.data_;
```suggestion
    data_ = rhs.data_;
```
Pointers copying here. No deep copy.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    if (data_ != nullptr) {
it not necessary. deleting nullptr is safe

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    return *this;
no deep copy, just shallow copy. Copy pointers, not data.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    if (data_) {
if not needed.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    delete data_;
you should not delete this memory. You just release the ownership and someone who obtains a raw pointer should call delete on it.

2020-09-20 19:56 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +    this->release();
not release, `delete data_;`

2020-09-21 18:02 UTC, WBigaj reviewed
I have checked your code and have nothing to add that have not been mentioned by other reviewers.

2020-09-28 11:38 UTC, mariuszlisowski commented on homework/unique_ptr/main.cpp
> +    int* ptr = ptr5.release();
I knew there was a leak and was looking for it inside header and forgot to check in main, poor me.

2020-09-28 11:38 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr(std::nullptr_t);
Ok

2020-09-28 11:42 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr(unique_ptr const&);
In the task description I read "Constructor copies a pointer" so I thought I'd need a copy constructor.

2020-09-28 11:43 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr& operator=(std::nullptr_t);
I read somewhere it may be useful to have such. But it's been removed.

2020-09-28 11:44 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr(unique_ptr const&);
Removed anyway.

2020-09-28 11:44 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    void reset(T*);
Done

2020-09-28 11:49 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    if (data_ != nullptr) {
I was not sure - thanks.

2020-09-28 11:50 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    return *this;
Shallow copy now.

2020-09-28 11:50 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    delete data_;
Done

2020-09-28 11:50 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    this->release();
Deleted

2020-09-28 11:51 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    if (data_) {
Removed

2020-09-30 09:54 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    unique_ptr(unique_ptr const&);
After watching 'Zarządzanie zasobami #2' I understood that unique must be unique (no copying allowed).

2020-09-30 09:56 UTC, mariuszlisowski commented on homework/unique_ptr/unique_ptr.hpp
> +    return *this;
'Zarządzanie zasobami #2' cleared why!

2020-10-14 10:37 UTC, ziobron requested changes
CI doesn't work because workflow file is in incorrect location. Please move it from homework/unique_ptr/.github/workflows/unique_ptr.yml to .github/workflows/unique_ptr.yml

2020-10-14 10:37 UTC, ziobron commented on homework/unique_ptr/unique_ptr-ut.cpp
> +}
there is a missing test on move assignment operator. You should have 2 initialized unique_ptrs (not nullptrs) and you move from one to another.

2020-10-22 05:47 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }
36 XP za implementację unique_ptra (3784)
3 XP za punktualność

2020-10-22 05:47 UTC, closed without merging