Md unique ptr
coders-school/memory-management pull request #32
Opened 2020-09-29 11:28 UTC by marcindus

My interpretation of unique_ptr. I was trying to avoid looking at solution from
Zarządzanie zasobami #2 ..  So propably i can improve this solution.

2020-09-29 11:46 UTC, WBigaj reviewed
I have checked your code and have one question.

2020-09-29 11:46 UTC, WBigaj commented on homework/unique_ptr/test.cpp
> +*/
What is that commentS?

2020-09-29 12:03 UTC, marcindus commented
I've created some test which will not compile since copy constructor and operator= are deleted in my_unique_ptr, i do not know how to test situation when compilation should fail

2020-09-30 15:51 UTC, MaciejSalamonski approved these changes

2020-09-30 15:51 UTC, MaciejSalamonski commented on homework/unique_ptr/my_unique_ptr.hpp
> +    T operator*() { return *ptr_; };
I think that return type should be T&. What if ptr is a nullptr?

2020-09-30 15:51 UTC, MaciejSalamonski commented on homework/unique_ptr/my_unique_ptr.hpp
> +    T* get() { return ptr_; }
Maybe get() const?

2020-09-30 15:51 UTC, MaciejSalamonski commented on homework/unique_ptr/my_unique_ptr.hpp
> +    void operator=(const my_unique_ptr<T>&) = delete;
Where is operator=(&&)?

2020-09-30 15:51 UTC, MaciejSalamonski commented on homework/unique_ptr/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.5)
I think you should add a workflow file (should contain valgrind) to prove that there are no memory leaks

2020-10-08 21:12 UTC, jakjan95 reviewed
Code looks good just add assignment operator and it will be perfect

2020-10-14 12:44 UTC, ziobron commented
> I've created some test which will not compile since copy constructor and operator= are deleted in my_unique_ptr, i do not know how to test situation when compilation should fail

In fact you cannot test it. You can test that compilation fails when there is a copying, but it's really not so important. Compiler will protect you writing not compiling code.

2020-10-14 13:10 UTC, ziobron requested changes
A few improvements are desired :)
Please also fix @MaciejSalamonski findings.

2020-10-14 13:10 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    int another_initial_value = 43;
you can create a test suite that will hold common things. You use such values across many tests.

2020-10-14 13:10 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    pointer_.reset(new int(another_initial_value));
test with empty reset would also be useful.

2020-10-15 05:01 UTC, ziobron requested changes
One missing test case.

2020-10-15 05:01 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    EXPECT_EQ(functionUptrAsArg(std::move(ptr)), m_someString);
please also add a test for move assignment. It will be called when you have already initialized unique_ptr and you move other initialized ptr into it.

2020-10-16 11:14 UTC, ziobron requested changes

2020-10-16 11:14 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +}
duplicated test?

2020-10-16 11:14 UTC, ziobron commented on homework/unique_ptr/test.cpp
> +    my_unique_ptr<SomeUsefulClass> ptr2 = std::move(m_sut);
this calls move constructor, not assignment operator. Assignment takes place when the object was already managing another memory. Do it in this way:
```suggestion
    my_unique_ptr<SomeUsefulClass> ptr2{new SomeUsefulClass{}};
    ptr2 = std::move(m_sut);
```

2020-10-22 05:55 UTC, ziobron requested changes

2020-10-22 05:55 UTC, ziobron commented on homework/unique_ptr/my_unique_ptr.hpp
> +    }
Valgrind claims that there are memory leaks in this move operator
https://github.com/marcindus/memory-management/runs/1269365447?check_suite_focus=true

You should delete a memory of the previously own object before assigning new value
And it should not return `T&`, but `my_unique_ptr<T>&`

```suggestion
    my_unique_ptr<T>& operator=(my_unique_ptr<T>&& ptr_m) noexcept
    {
        delete ptr_;
        ptr_ = ptr_m.release();
        return *this;
    }
```

2020-10-22 05:55 UTC, ziobron commented on homework/unique_ptr/my_unique_ptr.hpp
> +    void operator=(const my_unique_ptr<T>&) = delete;
```suggestion
    my_unique_ptr<T>& operator=(const my_unique_ptr<T>&) = delete;
```

2020-10-22 06:31 UTC, ziobron approved these changes
Good, no memory leaks :)

2020-10-22 06:32 UTC, ziobron commented
{ "requirement_ids": [3784] }
36 XP za implementację unique_ptra (3784)

2020-10-22 06:32 UTC, closed without merging