Homework2 - shared/weak/make_shared
coders-school/memory-management pull request #35
Opened 2020-10-07 07:02 UTC by anraf1001

Authors: @Vicx95, @jakjan95, @anraf1001

2020-10-08 08:08 UTC, J-Cieplinski commented on homework/shared_ptr/make_shared.hpp
> +    return ptr;
I'm pretty sure this construct will lead to memory leak. You reserve blockObject with new but I don't see any way you later free that memory with delete. This `ptr` and `object` from `blockObject` will exist indefinitely(or until program exits).

2020-10-08 09:35 UTC, anraf1001 commented on homework/shared_ptr/make_shared.hpp
> +    return ptr;
`ptr` and `controlBlock` are deallocated via shared_ptr or weak_ptr. We have build that project with leak sanitizer and there are no leaks.

2020-10-08 10:23 UTC, J-Cieplinski commented on homework/shared_ptr/make_shared.hpp
> +    return ptr;
How tho?
`  T object;
    SharedControlBlock<T> controlBlock;`

Can you deallocate those two with `delete T; delete controlBlock;`? It seems unlikely.

And running your tests i get
`[ RUN      ] MakeSharedTest.shouldCreateSharedPtrUsingMakeShared
munmap_chunk(): invalid pointer
Aborted (core dumped)`
And running with valgrind this passes(dunno how) but i get a bunch of invalid reads.

2020-10-08 10:32 UTC, J-Cieplinski commented on homework/shared_ptr/make_shared.hpp
> +    return ptr;
To clarify, I got rid of sanitizer before compiling.

2020-10-08 13:15 UTC, anraf1001 commented on homework/shared_ptr/make_shared.hpp
> +    return ptr;
> How tho?
T object; SharedControlBlock<T> controlBlock;
Can you deallocate those two with delete T; delete controlBlock;? It seems unlikely. They somewhat are created on the heap i think but it seems unintuitive

We send pointers to object and controlBlock and then delete it in shared/weak dtor. Deallocating object and controlBlock from blockObject is the same as deallocating whole structure at once.

> And running your tests i get
[ RUN ] MakeSharedTest.shouldCreateSharedPtrUsingMakeShared munmap_chunk(): invalid pointer Aborted (core dumped)

How have you done that? Even in github workflows there is no such an error

> Running with valgrind this passes(dunno how) but i get a bunch of invalid reads.

We are working on that

2020-10-08 13:33 UTC, J-Cieplinski commented on homework/shared_ptr/make_shared.hpp
> +    return ptr;
> How have you done that?

Deleted sanitizer link from cmake file, compiled and ran.

> Deallocating object and controlBlock from blockObject is the same as deallocating whole structure at once.

Yes but object and controlBlock in blockObject are just objects, not pointers. Would that mean that you can individually delete objects(not pointers) from a given struct if that struct was initialized as a pointer itself?

2020-10-10 00:36 UTC, MaciejSalamonski approved these changes
Nice code ;~}

2020-10-12 07:07 UTC, WojtekMs reviewed
Very nice code guys :)
I like your tests of breaking cyclic dependency and testing make_shared with an object that takes more than 1 parameter :)

2020-10-12 07:07 UTC, WojtekMs commented on homework/shared_ptr/shared_ptr.hpp
> +    }
I can see that controlBlock will delete ptr to data and there are no leaks, however this solution postpones releasing memory of data until there are no weak ptrs left, where it could be released as soon as there are no shared ptrs left [of course in case we do not use make_shared].

2020-10-12 07:07 UTC, WojtekMs commented on homework/shared_ptr/shared_ptr.hpp
> +    return *this;
remember to check if we are not self-moving
```cpp
auto shared = std::make_shared<int>(5);
shared = std::move(shared);
```

2020-10-14 09:13 UTC, WBigaj reviewed
Few suggestions from me.

2020-10-14 09:13 UTC, WBigaj commented on homework/shared_ptr/shared_ptr.hpp
> +    return 0;
```suggestion
    return controlBlock_ ?  (controlBlock_->getSharedRefs()) : 0;
```

2020-10-14 09:13 UTC, WBigaj commented on homework/shared_ptr/weak_ptr.hpp
> +    return 0;
```suggestion
    return controlBlock_ ? (controlBlock_->getSharedRefs()) : 0;
```

2020-11-03 13:44 UTC, ziobron requested changes
Really good implementation 👍 
Piece of good code :)
There are mainly some minor issues, however it would be nice to see strengthened tests.

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +}
Please add assertions on use_count in copy and move operations. You can merge it with below test

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +}
please add tests for move and copy assignment operators.

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/make_shared-ut.cpp
> +}
please also add reset operation on ptr and use_count before and after it to show that it can be safely destroyed

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/weak_ptr.hpp
> +}  // namespace cs
why is it needed here? Probably you need to move it to shared_ptr.hpp

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +}  // namespace cs
why is it needed here?

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    ASSERT_TRUE(isShared);
this assertion is always true (it's tautology). You may check if sptr2.get() is equal to sptr.get() or merge it with below test

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +TEST(WeakPtrTest, WeakPtrInitializedWithSharedAfterUseOfResetFunctionShouldDecrementUserCount) {
```suggestion
TEST(WeakPtrTest, WeakPtrInitializedWithSharedAfterUseOfResetFunctionShouldBeExpired) {
```

2020-11-03 13:44 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +}
you should also add use_count in these tests

2020-11-11 20:04 UTC, ziobron requested changes
Missing tests

2020-11-11 20:04 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +}
there are still copy constructor and copy assignment tests missing

2020-11-11 20:04 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +}
tests for copy/move assignments are missing. Please use shared_ptrs you will be moving-to already initialized with other resources to show that no resources are leaking on copy/move assignments.

2020-11-11 23:15 UTC, jakjan95 commented on homework/shared_ptr/weak_ptr-ut.cpp
> +}
done

2020-11-14 21:25 UTC, ziobron approved these changes
Well done 👍

2020-11-14 21:25 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    cs::weak_ptr<int> wptr2{};
would be better to have this wptr2 initialized with some other shared_ptr, not by default constructor, but let it be ;)

2020-11-14 21:26 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{
  "requirement_ids": [3794, 3795, 3796],
  "users": ["Vicx95", "jakjan95", "anraf1001"]
}

2020-11-14 21:26 UTC, closed without merging

2020-11-16 15:31 UTC, ziobron commented
{
"requirement_ids": [1636, 1119, 1119, 1119],
"users": ["Vicx95", "jakjan95", "anraf1001"]
}