Shared ptr
coders-school/memory-management pull request #36
Opened 2020-10-07 19:12 UTC by NeoBauer

#Marcinati
#NeoBauer

2020-10-08 01:42 UTC, MaciejSalamonski approved these changes
Hi! Good job 👍 Maybe implementation of operators= is a bit overcomplicated  but its fine. Have a nice day!

2020-10-08 01:42 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr.hpp
> +  if (rawPtr_) {
Isn't it better to just return rawPtr_?

2020-10-08 01:42 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr.hpp
> +template <typename T> T &SharedPtr<T>::operator*() const noexcept {
I suggest you to throw an exception. We cannot derefenrce a nullptr

2020-10-08 08:12 UTC, J-Cieplinski commented
I'm pretty sure at least some parts of those long `if else` blocks can be put into separate function. DRY

2020-10-08 21:06 UTC, jakjan95 reviewed
Some comments from me :)

2020-10-08 21:06 UTC, jakjan95 commented on homework/shared_ptr/SharedPtr.hpp
> +}
imo there is too much logic

2020-10-08 21:06 UTC, jakjan95 commented on homework/shared_ptr/SharedPtr.hpp
> +}
same here

2020-10-08 21:06 UTC, jakjan95 commented on homework/shared_ptr/SharedPtr.hpp
> +}
same here, you can see some pattern which you can separate do function

2020-10-14 08:53 UTC, WBigaj reviewed
Few suggestions from me.

2020-10-14 08:53 UTC, WBigaj commented on homework/shared_ptr/SharedPtr.hpp
> +        return nullptr;
return rawPtr_ ? rawPtr_ : nullptr;

2020-10-14 08:53 UTC, WBigaj commented on homework/shared_ptr/SharedPtr.hpp
> +        return *this;
You are returning *this regardless of result.Why do you repeat it everywhere?

2020-10-14 08:53 UTC, WBigaj commented on homework/weak_ptr/WeakPtr.hpp
> +    return true;
```suggestion
    return ControlBlock_ ? (useCount() == 0) : true;
```

2020-10-14 08:53 UTC, WBigaj commented on homework/weak_ptr/WeakPtr.hpp
> +    return SharedPtr<T>(*this);
```suggestion
    return expired() ?  SharedPtr<T>() : SharedPtr<T>(*this);
```

2020-11-03 15:04 UTC, ziobron requested changes

2020-11-03 15:04 UTC, ziobron commented on homework/weak_ptr/tests/tests.cpp
> +                REQUIRE(Catch::isOk);
you may check if weak ptr is not null

2020-11-03 15:04 UTC, ziobron commented on homework/weak_ptr/tests/tests.cpp
> +                REQUIRE(weakscooter.expired() == true);
check use count and if pointers are pointing to proper objects or merge it with below test

2020-11-03 15:04 UTC, ziobron commented on homework/weak_ptr/tests/tests.cpp
> +    GIVEN("Two SharedPtrs") {
there are 3 sharedPtrs below

2020-11-03 15:04 UTC, ziobron commented on homework/weak_ptr/tests/tests.cpp
> +                REQUIRE(weakscooter.expired() == false);
```suggestion
                REQUIRE_FALSE(weakscooter.expired());
```

2020-11-03 15:04 UTC, ziobron commented on homework/weak_ptr/tests/tests.cpp
> +}
lock() function is not tested.

2020-11-11 20:32 UTC, ziobron requested changes

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +            delete controlBlock_;
you release all resources only when there are no shared and weak pointers. std has another behavior. If there are no shared_ptrs resource is deleted (deleter is called) and when there are no shared and weak pointers - control block is removed.

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    SharedPtr<T> &operator=(const SharedPtr<T> &other);
please do not commit style changes. It makes code review so much harder.

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +            delete controlBlock_;
duplication (the same code in destructor). Extract to function.

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +            delete controlBlock_;
duplication (the same code in destructor). Extract to function.

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    if (other.rawPtr_ != rawPtr_)
```suggestion
    if (this != &other)
```

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +            controlBlock_ = other.controlBlock_;
rawPtr_ assignment is missing

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +        rawPtr_ = other.rawPtr_;
where is controlBlock assignment?

2020-11-11 20:32 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    if (NewRawPtr != rawPtr_)
no such check is needed here.

2020-11-11 20:32 UTC, ziobron commented on homework/weak_ptr/WeakPtr.hpp
> +    controlBlock_->weakRefsCounter_.exchange(controlBlock_->weakRefsCounter_.load(std::memory_order_relaxed) - 1,
```suggestion
    controlBlock_->weakRefsCounter_--
```
simple decrementation and incrementation works on atomics

2020-11-11 20:32 UTC, ziobron commented on homework/weak_ptr/WeakPtr.hpp
>          controlBlockRemover();
name your methods with verbs
decrementWeakCounter()
removeControlBlock()

2020-11-11 20:32 UTC, ziobron commented on homework/weak_ptr/WeakPtr.hpp
>  size_t WeakPtr<T>::useSCount() const noexcept {
std::weak_ptr has one function - use_count. It returns a number of shared counter.

2020-11-14 21:56 UTC, ziobron requested changes
Can you please fix it by tomorrow end of the day?

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    if (rawPtr != nullptr) {
no need for it. calling delete on nullptr is safe.

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +template <typename T> T &SharedPtr<T>::operator*() const noexcept {
std::shared_ptr does not throw an exception. It's fine and up to developers.

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    if(controlBlock_ == nullptr){
this if is not needed. You should always allocate a new ControlBlock, but if NewRawPtr == nullptr then it should have shared_refcount = 0 not 1.

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/tests/tests.cpp
> +    REQUIRE(NewSharedPtr.use_count() == 1);
```suggestion
    REQUIRE(NewSharedPtr.use_count() == 0);
```
AFAIK it should be 0 for nullptr. Please check with std::shared_ptr behavior

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/tests/tests.cpp
> +        REQUIRE(OldSharedPtr.get() == nullptr);
```suggestion
        REQUIRE(OldSharedPtr.get() == nullptr);
        REQUIRE(OldSharedPtr.use_count() == 0);
```

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/tests/tests.cpp
> +      THEN("scooter has power of NewScooter") {
there is still scooter in description

2020-11-14 21:56 UTC, ziobron commented on homework/shared_ptr/tests/tests.cpp
> +        REQUIRE(*(SharedOne.get()) == power2);
you can also check use_count before and after reset. 
Please also add a test when you use `reset()` (without argument). After such reset use_count should be 0.

2020-11-15 22:23 UTC, ziobron commented
Let me grant you only 50 XP for everything
{
  "requirement_ids": [3794],
  "points": [50],
  "users": ["Marcinati", "NeoBauer"]
}

2020-11-15 22:23 UTC, closed without merging

2020-11-16 15:32 UTC, ziobron commented
{
"requirement_ids": [1636],
"users": ["Marcinati", "NeoBauer"]
}