my_shared_ptr
coders-school/memory-management pull request #37
Opened 2020-10-10 22:05 UTC by marcindus

solution for memory management assessment,

2020-10-11 11:18 UTC, MaciejSalamonski approved these changes
Nice work ~;}

2020-10-14 08:48 UTC, WBigaj approved these changes
I have checked your code and it looks good 👍

2020-10-22 21:17 UTC, jakjan95 reviewed
for basic version of homework code looks good,  just try to improve tests - you have a few magic values :)

2020-11-04 14:58 UTC, ziobron requested changes

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    std::atomic<int> count_ = 0;
There should be also a second counter that counts weak_ptrs. And it should be unsigned like std::atomic<size_t>.

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        }
counter_ptr will always be nullptr in this constructor. You can remove this part.

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        this->counter_ptr = other_shared_ptr.counter_ptr;
it's better to do it on constructor initialization list

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        ptr_ = ptr_moved.get();
preferred way
```suggestion
        ptr_ = ptr_moved.ptr_;
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        }
this part is always false. You can remove it.

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +            counter_ptr->count_ = ptr_moved.use_count();
not this way. you should not create new Counter here. You should use the ptr_moved counter_ptr.

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        ptr_moved.reset(nullptr);
not reset. It's deleting memory. Move constructor should copy ptr and counter_ptr and set them to nullptr in source (ptr_moved)

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        delete counter_ptr;
it should be protected from self assignment (this == &other_shared_ptr)

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    };
this operator should return *this

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    T& operator=(const my_shared_ptr<T>&& some_ptr)
```suggestion
    T& operator=(my_shared_ptr<T>&& some_ptr)
```
move assignment operator takes non-const rvalue ref

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        if (some_ptr != this)
```suggestion
        if (&some_ptr != this)
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +            some_ptr.reset(nullptr);
nope. reset deletes the memory that your current pointer is pointing to.

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    int use_count() { return counter_ptr->count_; }
```suggestion
    size_t use_count() { return counter_ptr->count_; }
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    T operator*() { return *ptr_; };
```suggestion
    T& operator*() { return *ptr_; };
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    T* operator->() { return this->ptr_; };
```suggestion
    T* operator->() { return ptr_; };
```
You inconsistently use or use not `this` keyword. Either use it everywhere or remove it from everywhere (apart from `return *this;`)

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    EXPECT_EQ(ptr.use_count(), 2);
```suggestion
    my_shared_ptr<SomeUsefulClass>& another_ptr = ptr;
    EXPECT_EQ(ptr.use_count(), 1);  // ref does not create a copy
    
    my_shared_ptr<SomeUsefulClass> yet_another_ptr(another_ptr);
    EXPECT_EQ(another_ptr->message_, "");
    EXPECT_EQ(ptr.use_count(), 2);
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    EXPECT_EQ(ptr->message_, m_msg);
```suggestion
    my_shared_ptr<SomeUsefulClass>&& ptr = std::move(m_sut);
    EXPECT_EQ(m_sut.get(), nullptr);
    EXPECT_NE(ptr.get(), nullptr);
    EXPECT_EQ(ptr->message_, m_msg);
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +TEST_F(SharedPointerTestSuite, moveAssigmenOperator)
it's a test for move constructor. Move assignment operator is called when you have already initialized object and you assign a new value for it. The same for copy operation. Like:
```cpp
int a = 5;
a = 6;  // copy assignment
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +}
wasn't this already tested?

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +}
it's copy constructor called there. 
```suggestion
TEST_F(SharedPointerTestSuite, asgnOperator)
{
    auto copy_ptr = my_shared_ptr<SomeUsefulClass>(new SomeUsefulClass{});
    copy_ptr = m_sut;  // this calls copy assignment operator
    EXPECT_EQ(copy_ptr.use_count(), 2);
}
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +TEST_F(SharedPointerTestSuite, CopyConstructor)
you are testing bool conversion here. Add an example when it gives `false`.

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    EXPECT_EQ(*(pointer_.get()), new_value);
```suggestion
    EXPECT_EQ(*pointer_, new_value);
```

2020-11-04 14:58 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    m_sut.reset(nullptr);
also when nothing is passed the behavior should be the same as for nullptr. Just add a default argument value in reset definition.

2020-11-05 09:14 UTC, ziobron requested changes

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
>          delete counter_ptr;
No, not exactly deletion. The procedure is the same as for destructor. Decrement shared_count and check if you can delete memory. If counter is not equal to zero you should not delete it. The best way is to create a private function that does such thing and call it in destructor and here.

And protection against self-assignment needs to be added - `if (this != &other_shared_ptr)`

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +            counter_ptr->weak_count++;
do not increement weak_count

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
>          delete ptr_;
not delete, procedure is the same as for calling a destructor

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
>          counter_ptr->count_ = 0;
```suggestion
        counter_ptr->count_ = 1;
```
You will have one pointer pointing to it

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> -        counter_ptr->count_--;
why this is deleted? it was fine

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +            counter_ptr->weak_count--;
generally logic here is incorrect. First decrement counter_ptr->count_, then check if it's equal to 0 and if it is delete ptr_. If both count_ and weak_count are equal to 0 delete counter_ptr.

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    T* operator->() { return ptr_; };
```suggestion
    T& operator*() const { return *ptr_; };
    T* operator->() const { return ptr_; };
```

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
>              delete counter_ptr;
do not delete anything in move operation. https://github.com/coders-school/memory-management/blob/master/module2/smart_pointers_implementation_details.md

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +            some_ptr = nullptr;
not this way. 
```suggestion
            some_ptr.ptr_ = nullptr;
            some_ptr. counter_ptr = nullptr;
```

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    ASSERT_FALSE(some_ptr);
```suggestion
    my_shared_ptr<SomeUsefulClass> some_ptr = my_shared_ptr<SomeUsefulClass>(new SomeUsefulClass());;
    my_shared_ptr<SomeUsefulClass> another_ptr = my_shared_ptr<SomeUsefulClass>(new SomeUsefulClass());;
    another_ptr  = std::move(some_ptr);  // now we have move assignment
    EXPECT_EQ(another_ptr->message_, "");
    EXPECT_EQ(some_ptr.get(), nullptr);
    ASSERT_FALSE(some_ptr);
```

2020-11-05 09:14 UTC, ziobron commented on homework/shared_ptr/test.cpp
>      ASSERT_TRUE(copy_ptr);
add a case when conversion gives false
```suggestion
    my_shared_ptr<int> copy_ptr = my_shared_ptr<int>(ptr);
    ASSERT_TRUE(copy_ptr);
    copy_ptr.reset();
    ASSERT_FALSE(copy_ptr);
```

2020-11-05 22:51 UTC, marcindus commented on homework/shared_ptr/my_shared_ptr.hpp
>              delete counter_ptr;
Fixed.Did my best but still  I am not sure if there is something to fix. 
 so I have proposal, if my code  still is completely screwed up lets skip next review and talk about it during simulated job interview

2020-11-07 09:38 UTC, ziobron requested changes
Almost good. The implementation looks correct, there is only one issue from me :)
You need to add 1 tests and make some small corrections.

2020-11-07 09:38 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +    size_t use_count() { return counter_ptr->count_; }
```suggestion
    size_t use_count() { 
        if (ptr_) {
            return counter_ptr->count_;
        } else {
            return 0;
        }
```
This is a protection against reset operation, where you allocate a new control block with shared_refs = 1, even if you have nullptr. It may be solved in other ways too, eg. use the constructor of the control block that takes 0 as an argument.
Add checking it in ShouldResetWithNullptr test.

2020-11-07 09:38 UTC, ziobron commented on homework/shared_ptr/test.cpp
> -
I don't see a need for removing this test. It was a good one.

2020-11-07 09:38 UTC, ziobron commented on homework/shared_ptr/test.cpp
>      ASSERT_FALSE(some_ptr);
add an assertion on use_count here. Move operations should not increase it.
Also please add the same scenario for move constructor, which is now missing in tests.

2020-11-11 21:09 UTC, ziobron approved these changes

2020-11-11 21:09 UTC, ziobron commented on homework/shared_ptr/my_shared_ptr.hpp
> +        ptr_ = nullptr;
ok, but it should be initialized on init list

2020-11-11 21:09 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    my_shared_ptr<SomeUsefulClass> another_ptr = my_shared_ptr<SomeUsefulClass>(std::move(some_ptr));;
hmm... interesting code. You have used both copy and move constructors in one line :D 
Probably you have just meant to use only move constructor like below.
```suggestion
    my_shared_ptr<SomeUsefulClass> another_ptr = std::move(some_ptr);
```

Anyway, move c-tor was used :D

2020-11-11 21:09 UTC, ziobron commented on homework/shared_ptr/test.cpp
>      m_sut.reset(nullptr);
```suggestion
    m_sut.reset();
```

2020-11-11 21:11 UTC, ziobron commented
{ "requirement_ids": [3794] }
50 XP za implementację shared_ptra (3794)

2020-11-11 21:11 UTC, closed without merging

2020-11-16 15:32 UTC, ziobron commented
{
"requirement_ids": [1119],
}

2020-11-16 15:34 UTC, ziobron commented
{
"requirement_ids": [1119]
}