Shared ptr + weak ptr
coders-school/memory-management pull request #38
Opened 2020-10-11 11:39 UTC by MonikaZelechowska

2020-10-11 11:52 UTC, MaciejSalamonski approved these changes
Good job :+1:

2020-10-13 22:16 UTC, J-Cieplinski commented on exercises/uniquPointer.cpp
> +void testStarOperator()
Why all of those test functions here?

2020-10-13 22:16 UTC, J-Cieplinski commented on exercises/uniquPointer.cpp
> +    {std::cout<<"konstruktor"<<std::endl;}
Is that necessary here?

2020-10-13 22:16 UTC, J-Cieplinski commented on exercises/uniquPointer.cpp
> +    return *(this->pointer);
dereferencing a nullptr

2020-10-14 08:46 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-10-14 08:46 UTC, WBigaj commented on exercises/List.cpp
> +        }
```suggestion
        temp = temp->prev;
```

2020-10-14 08:46 UTC, WBigaj commented on exercises/List.cpp
> +        }
This else is redundant since return would escape function.

2020-10-14 08:46 UTC, WBigaj commented on exercises/uniquPointer.cpp
> +    {std::cout<<"konstruktor"<<std::endl;}
+1

2020-10-14 08:46 UTC, WBigaj commented on exercises/uniquPointer.cpp
> +void testStarOperator()
I agree with @J-Cieplinski. Tests should be in antoher file.

2020-11-04 21:09 UTC, ziobron requested changes
There are problems with memory that are reported by valgrind:
https://github.com/MonikaZelechowska/memory_management/runs/1238041615?check_suite_focus=true

Apart from that very clean code and tests 👍

2020-11-04 21:09 UTC, ziobron commented on homework/shared_ptr/WeakPtr.hpp
> +    if (controlBlock_ != nullptr) {
what about calling `handleWeakPtrAndControlBlockDelete();`? We may already own an object.

2020-11-04 21:09 UTC, ziobron commented on homework/shared_ptr/WeakPtr.hpp
> +    if (&otherWeakPtr != this) {
what about calling `handleWeakPtrAndControlBlockDelete();`? we may already own an object.

2020-11-04 21:09 UTC, ziobron commented on homework/shared_ptr/WeakPtr-ut.cpp
> +    ASSERT_EQ(testWeakPtr.use_count(), testSharedPtr.use_count());
you should also check if use_count on weak_ptr drops to zero after resetting shared_ptr and epxired returns true

2020-11-04 21:09 UTC, ziobron commented on homework/shared_ptr/WeakPtr-ut.cpp
> +    ASSERT_FALSE(testWeakPtr.expired());
you can check if both of them points to the same data. The same for below test.

2020-11-04 21:09 UTC, ziobron commented on homework/shared_ptr/WeakPtr-ut.cpp
> +    ASSERT_FALSE(testWeakPtr.expired());
we should test emptyWeakPtr here and it should be true.

2020-11-11 21:48 UTC, ziobron requested changes

2020-11-11 21:48 UTC, ziobron commented on homework/shared_ptr/SharedControlBlock.hpp
> +    std::function<void(T*)> defaultDeleter = [](T* ptr = nullptr) { delete ptr; };
this hides members from a base class. You should rather remove it from a base class.

2020-11-11 21:48 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +        : shControlBlock_(newBlock) { ptr_ = newBlock->getObj(); }
do everything on init list

2020-11-11 21:48 UTC, ziobron commented on homework/shared_ptr/SharedControlBlock.hpp
> +        : object_(args...) {}
also, a deleter should be overridden to not delete anything.

2020-11-11 21:48 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +}
what if weak_ptr is expired? we should be protected against it.

2020-11-11 21:48 UTC, ziobron commented on homework/shared_ptr/MakeShared-ut.cpp
> +}
please add tests for copying and moving shared_ptrs created by make_unique. They handle resources in a different way.

2020-11-14 22:07 UTC, ziobron approved these changes
Well done :)

2020-11-14 22:07 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796] }

2020-11-14 22:07 UTC, closed without merging

2020-11-16 15:33 UTC, ziobron commented
{
"requirement_ids": [1119, 1119, 1119]
}