SharedPointer, WeakPointer, MakeShared implementations homework
coders-school/memory-management pull request #40
Opened 2020-10-11 17:58 UTC by Kasperice

Authors: @pawellos, @damixior, @kasperice

We created some implementations of above structures, but we encountered some problems so if you spot any mistake please let us know ;) Then we will try to correct it of course

2020-10-11 20:03 UTC, MaciejSalamonski approved these changes
Nice work :)

2020-10-11 23:05 UTC, WojtekMs reviewed
Good code guys :)

2020-10-11 23:05 UTC, WojtekMs commented on homework/shared_ptr/WeakPointer.hpp
> +    ptr_ = anotherPtr.ptr_;
remember to decrease weak ptr count before changing refCounter

2020-10-11 23:05 UTC, WojtekMs commented on homework/shared_ptr/WeakPointer.hpp
> +
remember to check if you are not self-assigning and to decrease weak count before changing refCounter

2020-10-12 05:24 UTC, Kasperice commented on .github/workflows/shared.yml
> +name: Unique Ptr CMake CI
Thanks ;)

2020-10-12 08:07 UTC, Kasperice commented
@WojtekMs thank you for all your comments, we are going to try to resolve them :)

2020-10-14 08:41 UTC, WBigaj reviewed
One question from me.

2020-10-14 08:41 UTC, WBigaj commented on homework/shared_ptr/ControlBlock.hpp
> +    // auto defaultDeleter = [](T* ptrToDelete) { delete ptrToDelete;};
What is this?

2020-10-14 08:43 UTC, Kasperice commented on homework/shared_ptr/ControlBlock.hpp
> +    // auto defaultDeleter = [](T* ptrToDelete) { delete ptrToDelete;};
It is a comment. We are still working on @WojtekMs suggestions

2020-10-22 21:16 UTC, jakjan95 reviewed
Code looks good, just few magic values in tests to fix :)

2020-10-22 21:16 UTC, jakjan95 commented on homework/shared_ptr/tests.cpp
> +    ASSERT_EQ(testControlBlock.getWeak(), 0);
magic values in tests

2020-10-23 06:55 UTC, Kasperice commented on homework/shared_ptr/tests.cpp
> +    ASSERT_EQ(testControlBlock.getWeak(), 0);
Thanks, resolved

2020-11-04 22:40 UTC, ziobron requested changes

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +}
Good point @WojtekMs, it should be handled properly. Please add a test for it.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +        throw NullPtrException("Dereference null pointer !");
it's not normal shared_ptr behavior, but I understand that you yours to work differently ;)

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +    }
what is returned if we have self assignment? We should as well return *this

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +        refCounter_->decreaseShared();
checkControlBlock already decreases this counter
```suggestion
```

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +        refCounter_->decreaseShared();
checkControlBlock already decreases this counter

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +    WeakPointer(WeakPointer& anotherPtr);
```suggestion
    explicit WeakPointer(const SharedPointer<T>& sharedPtr);
    WeakPointer(const WeakPointer& anotherPtr);
```

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +    SharedPointer<T> lock();
```suggestion
    size_t use_count() const noexcept;
    bool expired() const noexcept;
    SharedPointer<T> lock() const noexcept;
```

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +    T* get();
```suggestion
    T* get() const;
```

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +    WeakPointer<T>& operator=(WeakPointer<T>& anotherPtr);
```suggestion
    WeakPointer<T>& operator=(const SharedPointer<T>& anotherPtr);
    WeakPointer<T>& operator=(const WeakPointer<T>& anotherPtr);
```

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +        delete refCounter_;
refCounter_ calls deleter in it's destructor. I need to see the test what happens when we remove last shared_ptr and we have only weak_ptr observing the memory. I can smell a double free problem.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +        checkControlBlock();
why not add decreasing weak into checkControlBlock? They should go in pair everywhere.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +    return nullptr;
implicit conversion form nullptr to SharedPtr

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +    refCounter_->decreaseWeak();
where is `checkControlBlock();`?

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +        ptr_ = anotherPtr.ptr_;
what about the old resource? We should handle deletion properly - checkControlBlock(); and decreaseWeak()

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +        ptr_ = anotherPtr.ptr_;
the same here. Deletion of control block of previously observed resource should be handled here

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +};
you could split this test file by tested class.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +}
add use_counts into these tests to show what happens

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    s_ptr.reset();
reset with argument should also be tested

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +
move and copy assignment operators are not tested

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    WeakPointer<int> w_ptr{};
this name hides the one from a test fixture. Avoid it.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    auto s_ptrNew = w_ptr.lock();
test for calling lock when there is no shared_ptr is also needed.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    ASSERT_TRUE(w_ptr.expired());
```suggestion
    ASSERT_TRUE(w_ptr.expired());
    ASSERT_FALSE(w_ptrNew.expired());
```

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    WeakPointer<int> w_ptrNew{};
please use a constructor that creates not expired WeakPointer. I can smell memory issues.

2020-11-04 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    WeakPointer<int> w_ptrNew{};
the same here. Copy into weak_ptr that is already observing something.

2020-11-11 22:40 UTC, ziobron requested changes
+1 for comparison with std

2020-11-11 22:40 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
>  }
what if weakPointer was expired? We should have protection against it. Add a proper test.

2020-11-11 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    SharedPointer<int> newPtr;
please use shared_ptr that already manages some memory.
```suggestion
    SharedPointer<int> newPtr{new int{}};
```

2020-11-11 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +    SharedPointer<int> newPtr;
please use shared_ptr that already manages some memory.
```suggestion
    SharedPointer<int> newPtr{new int{}};
```

2020-11-11 22:40 UTC, ziobron commented on homework/shared_ptr/tests.cpp
> +}
add one more test. it should start like this one, but then call reset on shared_ptr (shared_ref == 0) and then copy and move weak_ptr and try to get shared_ptrs from them.

2020-11-13 07:45 UTC, Kasperice commented on homework/shared_ptr/SharedPointer.hpp
> +        ptr_ = refCounter_->getData();
when we are using init list we encounter a problem with initialization order, I did not found any better solution yet

2020-11-14 21:45 UTC, Kasperice commented
I think that is all we could do for now. There are still some comments open, but it will be impossible for us to resolve them in a few days :/

2020-11-14 22:38 UTC, ziobron requested changes
it's almost ok. Please fix my findings and add one more test with weak_ptrs - call reset on shared_ptr (shared_ref == 0) and then copy and move weak_ptr and try to get shared_ptrs from them.

2020-11-14 22:38 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isInitialized_ = true;
it's not true. Your control block should be initialized even if there are 0 arg used. The default constructor of T will be used.

2020-11-14 22:38 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isInitialized_ = true;
it's not true. Your control block should be initialized even if there are 0 arg used. The default constructor of T will be used.

2020-11-14 22:38 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +        }
no, the previous version was ok.

2020-11-14 22:38 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +        checkControlBlock();
do it before you reassign resources. It should work for the old resource.
```suggestion
        checkControlBlock();
        ptr_ = anotherPtr.ptr_;
        refCounter_ = anotherPtr.refCounter_;
        refCounter_->increaseWeak();
```

2020-11-14 22:38 UTC, ziobron commented on homework/shared_ptr/WeakPointer.hpp
> +        checkControlBlock();
the same here.

2020-11-14 22:38 UTC, ziobron commented
@Pawellos, @DamiXioR, @Kasperice if you are able to fix my finding until tomorrow end of the day you will get all points.

2020-11-15 09:41 UTC, DamiXioR commented on homework/shared_ptr/SharedPointer.hpp
> +        }
in previous version every shared pointer initialized (also with nullptr), show that one shared reference is exist. In this version we changed if only initialized shared set shared refs with 1, no argument constructor, and constructor which take pointer set on nullptr don't set shared ref with 1.

2020-11-15 15:46 UTC, Kasperice commented on homework/shared_ptr/ControlBlock.hpp
> +            isInitialized_ = true;
@DamiXioR fixed it

2020-11-15 15:51 UTC, DamiXioR commented on homework/shared_ptr/ControlBlock.hpp
> +            isInitialized_ = true;
This variable is helpful because we check if is no args constructor called. If it's true that mean we have nullptr so shared refs should be equal 0

2020-11-15 15:57 UTC, Kasperice commented
@ziobron we tried to fix everything, I hope we understood you correctly ;)

2020-11-15 16:11 UTC, DamiXioR commented on homework/shared_ptr/ControlBlock.hpp
> +            isInitialized_ = true;
Every time Control Block is initialized but whis variable means that we have no args so ptr should be nullptr. I used confusing variable name. Now is fixed.

2020-11-15 21:47 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isInitialized_ = true;
I am still not convinced. This constructor will be used only in make_shared and it tells how many arguments were passed to make_shared. You can normally create a shared_ptr to int with passing no parameters - `auto ptr = make_shared<int>();`. Here you always have your object T. It is always initialized, because it is not pointer.

2020-11-15 21:54 UTC, ziobron requested changes

2020-11-15 21:54 UTC, ziobron commented on homework/shared_ptr/SharedPointer.hpp
> +        else {
no, this is used in make_shared only so you will always have an object. Even if isAnyArgumentPassInConstrutor is false. Your behavior is incorrect here.

2020-11-15 21:54 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
No, just remove it. Do you have any evidence (test) showing that your version is correct? data_ is always initialized and you cannot have a nullptr in ControlBlockData because it contains not a pointer, but just data.

2020-11-15 21:57 UTC, DamiXioR commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
We had problem because when we dont pass any arguments it's initialized our pointer with trash data.

2020-11-15 22:07 UTC, DamiXioR commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
The last one test:
TEST(MakeSharedTest, shouldUseMakeSharedWithNoArguments) {
    auto ms_ptr = MakeShared<int>();
    ASSERT_EQ(ms_ptr.get(), nullptr);
    ASSERT_EQ(ms_ptr.use_count(), noReferences);
}

2020-11-15 22:11 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
It should not be initialized with trash. Just in case you can replace `data_(std::forward<Args>(args)...)` with `data_{std::forward<Args>(args)...}` or add default constructor (taking no params) to check it.

2020-11-15 22:17 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
What about such test:
```cpp
TEST(MakeSharedTest, shouldUseMakeSharedWithNoArguments) {
    auto ms_ptr = MakeShared<int>();
    ASSERT_EQ(*ms_ptr, 0);
    ASSERT_EQ(ms_ptr.use_count(), oneReference);
}
```

2020-11-15 22:27 UTC, DamiXioR commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
when i removed that bool variable we get segmentation fault :(

2020-11-15 22:39 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
Hmm... you need to debug it to get to know the issue. I would like to have a test as I pasted above to be working. 
Do you want to try to fix it? I can give you more time.
If not I will not grant you points for make_shared. Only for shared and weak ptrs. The choice is yours :)

2020-11-15 22:43 UTC, DamiXioR commented on homework/shared_ptr/ControlBlock.hpp
> +            isWithArgs_ = true;
Ok now it works. I hope :)

2020-11-15 22:55 UTC, ziobron approved these changes
Good job 👍

2020-11-15 22:56 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796] }

2020-11-15 22:56 UTC, closed without merging

2020-11-15 22:59 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796], "users": ["Pawellos", "DamiXioR"] }

forgot about others ;)

2020-11-16 15:34 UTC, ziobron commented
{
"requirement_ids": [1636, 1119, 1119, 1119],
"users": ["Pawellos", "DamiXioR", "Kasperice"]
}