SharedPtr Homework
coders-school/memory-management pull request #41
Opened 2020-10-11 18:38 UTC by MaciejSalamonski

2020-10-14 08:35 UTC, WBigaj approved these changes
I have checked your code and it looks good 👍

2020-10-22 21:13 UTC, jakjan95 approved these changes
For me code looks good :)

2020-11-05 11:40 UTC, ziobron requested changes
unique_ptr should not be commited to this PR

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    }
if CounterBlock would be by default initialized with 1 there will be no need to `incrementCounter()`.

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    counter_ = otherPtr.counter_;
you can move this operations on constructor initializer list

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +        throw InvalidDereference("You can not derefernce a nullptr!");
it's not a normal shared_ptr behavior. I guess that you wanted to it in your way.

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    delete ptr_;
what about calling your deleter() here instead of delete? You will have problems when you call reset when there are 2 or more shared_ptrs to the same resource. Please add a test for this case and fix it.

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    EXPECT_EQ(*copyOfTestPtr, testingValue);
please add assertions on use_count before and after copy and merge it with below test

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    testSharedPtr_.reset(new int{testingValue});
you should also add test for calling reset without argument - `reset()`

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    EXPECT_EQ(*moveTestingPtr, testingValue);
please add assertions on use_count before and after move

2020-11-05 11:40 UTC, ziobron commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    coders_school::shared_ptr<int> moveTestingPtr = std::move(testSharedPtr_);
this is the same as above - move constructor is called. To have move assignment called you need first to initialize your pointer with another value.
```suggestion
    auto moveTestingPtr = coders_school::shared_ptr<int>{4};
    moveTestingPtr = std::move(testSharedPtr_);
```

2020-11-07 02:47 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr.hpp
> +    delete ptr_;
done

2020-11-07 02:49 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr.hpp
> +        throw InvalidDereference("You can not derefernce a nullptr!");
Delete that throw?

2020-11-07 02:53 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr.hpp
> +    }
Unfortunately I have to leave it like this :(. It would make a lot of changes. Unfortunately this weekend I don't have time to fix it

2020-11-07 02:54 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    EXPECT_EQ(*moveTestingPtr, testingValue);
done

2020-11-07 02:54 UTC, MaciejSalamonski commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    testSharedPtr_.reset(new int{testingValue});
done

2020-11-07 03:03 UTC, MaciejSalamonski commented on homework/shared_ptr/CounterBlock.hpp
> +constexpr unsigned int counterValueAfterReset = 1;
I changed that a bit, but there is still a lot of redundant code that is difficult to refactor. Unfortunately, in my opinion selecting these values ​​complicated the whole code. To fix this, I'd have to change almost every feature. It would be best to rewrite this program, but unfortunately I don't have time for that anymore.

2020-11-12 15:23 UTC, ziobron approved these changes

2020-11-12 15:23 UTC, ziobron commented on homework/shared_ptr/SharedPtr-ut.cpp
> +    coders_school::shared_ptr<int> thirdUse = multipleUsesTest;
these pointers are not checked if they are still valid

2020-11-12 15:23 UTC, ziobron commented on homework/shared_ptr/SharedPtr.hpp
> +    delete ptr_;
Not done? I can still see bare delete.
It's easy to fix, so let me approve this PR.

2020-11-12 15:24 UTC, ziobron commented
{ "requirement_ids": [3794] }
50 XP za implementację shared_ptra (3794)

2020-11-12 15:24 UTC, closed without merging

2020-11-16 15:35 UTC, ziobron commented
{
"requirement_ids": [1119]
}