Smart Pointers Homework
coders-school/memory-management pull request #42
Opened 2020-10-11 21:39 UTC by WojtekMs

- shared_ptr
- weak_ptr
- make_shared

2020-10-12 06:17 UTC, MaciejSalamonski approved these changes
Everything looks good :p

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/shared.hpp
> +    T& operator*() noexcept { return *data_; }
dereferencing a nullptr

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/shared.hpp
> +    return *this;
```suggestion
    if (this != &rhs) {
        releaseMemory();
         data_ = rhs.data_;
         controlBlock_ = rhs.controlBlock_;
         if (controlBlock_) {
             controlBlock_->incrementSharedRef();
         }
    }
    return *this;
```

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/shared.hpp
> +shared_ptr<T>& shared_ptr<T>::operator=(shared_ptr&& rhs) noexcept
same here

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/shared.hpp
> +                controlBlock_ = nullptr;
So this first `if` is only called when there is an object. Then you check if there are any shared_ptr and delete whole control block along with that object. Only then if there is no object you check if there are any shared_ptr pointing at it and delete that object(one that  already doesn't exist)?

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/shared.hpp
> +    if (controlBlock_->getObject()) {
If `data_` and `controlBlock_->getObject()` are holding the same thing, why not just `if(data_)`?

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/weak.hpp
> +weak_ptr<T>& weak_ptr<T>::operator=(const weak_ptr<T>& rhs) noexcept {
Same thing as with shared_ptr

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/weak.hpp
> +weak_ptr<T>& weak_ptr<T>::operator=(weak_ptr<T>&& rhs) noexcept
as above

2020-10-13 22:00 UTC, J-Cieplinski commented on homework/shared_ptr/controlObject.hpp
> +// }
Comments

2020-10-14 07:43 UTC, WBigaj reviewed
I have checked your code and have nothing to add that was not mentioned by previous reviewers.

2020-10-14 15:44 UTC, WojtekMs commented on homework/shared_ptr/shared.hpp
> +                controlBlock_ = nullptr;
No. This call `controlBlock_->getObject()` is in fact checking if shared_ptr was created by make_shared. In case it was created by make_shared, controlBlock will own the object and return it's address (not nullptr), in that case all I have to do is delete controlBlock [because it owns object it will delete object on it's own].
In case `controlBlock->getObject()` returns nullptr it means that my shared_ptr was not created by make_shared and controlBlock does not own an object. Due to this fact I have to delete both the object (data_) and controlBlock. But I can delete data_ only when there are no other shared_ptrs pointing to it. Similarly I can delete controlBlock only when there are no other weak_ptrs pointing to it

2020-10-14 15:46 UTC, WojtekMs commented on homework/shared_ptr/shared.hpp
> +    return *this;
This is not obligatory. I prefer to write code in functions this way:
1) validate arguments
2) perform action
It's true that I have 2 return statements but in a short function like this it is not a problem, and keeping to this convention helps me to remember about validating arguments every time. Additionally my code is not nested inside if statement

2020-10-14 15:49 UTC, WojtekMs commented on homework/shared_ptr/shared.hpp
> +    if (controlBlock_->getObject()) {
`data_` and `controlBlock_->getObject()` are holding the same thing only when shared_ptr was created by make_shared. In case it was created by it's constructor then `controlBlock_->getObject()` would return nullptr whereas `data_` would hold the address of the object.

2020-10-14 15:54 UTC, WojtekMs commented on homework/shared_ptr/controlObject.hpp
> +// }
Thanks, I missed it

2020-10-14 15:54 UTC, WojtekMs commented on homework/shared_ptr/shared.hpp
> +    T& operator*() noexcept { return *data_; }
According to: [cppreference](https://en.cppreference.com/w/cpp/memory/shared_ptr/operator*) it is undefined behavior if the stored pointer is null. I'm implementing std::shared_ptr, that's why I will leave it like that.

2020-10-22 21:12 UTC, jakjan95 approved these changes
Code looks good, just little comment from me

2020-10-22 21:12 UTC, jakjan95 commented on homework/shared_ptr/control.hpp
> +};
i would rather use here scissors rule(first public then private)

2020-10-24 08:48 UTC, WojtekMs commented on homework/shared_ptr/control.hpp
> +};
Okay, thank you for your suggestion, but what is the benefit of this approach?

2020-11-05 13:29 UTC, ziobron requested changes
Nice implementation. You have really good tests on ref counting 👍 
Thanks @J-Cieplinski for insightful review and @WojtekMs for accurate answers 👍
I was able to find 1 major issue in make_shared.

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +}
There is no need to put `shared` in every test name

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +    test->use();
there are no assertions so generally everything can pass this test. Checking value returned from use could do the job.

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +    EXPECT_EQ(test, false);
or just EXPECT_TRUE and EXPECT_FALSE, which are the preferred way.

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +}
Big 👍  for this test. Many people are not testing custom deleters.
However your test does not check it this deleter was in fact called. Of course valgrind can tell you if there are memory leaks, but if your deleter can change capture local bool value and change it, you could detect that it was indeed called.
You can do the same in resetCanBeUseWithCustomDeleter

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +}
great test!

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +    EXPECT_EQ(emptyShared1.get(), nullptr);
you can also check use_count before and after copy

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/weak.hpp
> +
```suggestion
```

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/weak_tests.cpp
> +}
please add some assertions, eg. on `expired()` (or merge it some futher tests)

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/weak_tests.cpp
> +    EXPECT_EQ(ptr.expired(), false);
you may use EXPECT_FALSE / TRUE here and somewhere below

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/weak_tests.cpp
> +    EXPECT_EQ(defaultShared.use_count(), expectedUseCount);
you can copy a weak_ptr here and check if use_count has not incremented, but it is incremented when a copy of shared_ptr is made.

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/weak_tests.cpp
> +    EXPECT_EQ(ptr.lock(), defaultShared);
do we have comparison operator on shared_ptrs? Does it work as expected? I guess I have not seen your implementation. You can of course compare dereferenced objects.

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/weak_tests.cpp
> +}
copy of lockShouldReturnNullptrWhenNoManagedObject (line 59)

2020-11-05 13:29 UTC, ziobron commented on homework/shared_ptr/tests/weak_tests.cpp
> +TEST_F(WeakTest, copyAssignmentShouldIncreaseWeakRefCount) {
this name is not corresponding with what this test does check. Neither a few below tests where you mention WeakRefCount. It's in control block and we have no way to check it here.

2020-11-05 21:13 UTC, WojtekMs commented on homework/shared_ptr/bad_weak_ptr.hpp
> +        }
However, if I inherit from std::exception and I do not override `what()` method, it is printing std::exception not my own cs::bad_weak_ptr type

2020-11-05 22:18 UTC, WojtekMs commented on homework/shared_ptr/shared.hpp
> +    shared_ptr(control_block<T>*) noexcept;
In my implementation of make_shared
```cpp
template <typename T, typename... Ts>
shared_ptr<T> make_shared(Ts&&... args)
{
    return shared_ptr<T>{new controlObject<T, Ts...>(std::forward<Ts>(args)...)};
}
I create shared_ptr out of controlObject, which is derived from control_block.
```

2020-11-05 22:29 UTC, WojtekMs commented on homework/shared_ptr/tests/weak_tests.cpp
> +}
Good point, the test lockShouldReturnNullptrWhenNoManagedObject was supposed to reset shared_ptr not weak_ptr

2020-11-05 22:34 UTC, WojtekMs commented on homework/shared_ptr/tests/weak_tests.cpp
> +TEST_F(WeakTest, copyAssignmentShouldIncreaseWeakRefCount) {
You are right. I corrected this test name, but when it comes to checking if memory is released when we use copy / move operators it can be only checked by valgrind and ie. weakWhenCopiedShouldReleaseMemoryWhenIsTheLastWeakPtrAndSharedCountIs0 test scenario is created for this purpose.

2020-11-05 22:39 UTC, WojtekMs commented
As requested:
- make_shared fix + tests checking many arguments are added
- bad_weak_ptr what override removed [but now what method returns `std::exception` instead of `std::bad_weak_ptr`
- comparing of 2 shared_ptr's is corrected - now dereferenced shared_ptrs are compared
- misleading test name corrected

2020-11-05 22:41 UTC, WojtekMs commented on homework/shared_ptr/tests/weak_tests.cpp
> +    EXPECT_EQ(ptr.lock(), defaultShared);
There is no operator== implemented for `cs::shared_ptr`. I guess they must've been converted to boolean values and then compared

2020-11-05 22:42 UTC, WojtekMs commented on homework/shared_ptr/bad_weak_ptr.hpp
> +        }
However, if I remove my implementation `what()` returns `std::exception` instead of `std::bad_weak_ptr`

2020-11-12 15:26 UTC, ziobron commented on homework/shared_ptr/bad_weak_ptr.hpp
> +        }
how/where do you catch it?

2020-11-12 15:27 UTC, ziobron commented on homework/shared_ptr/tests/shared_tests.cpp
> +}
Maybe you get std::exception on the output because of this?

2020-11-12 15:35 UTC, ziobron approved these changes
Good job 👍

2020-11-12 15:36 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796] }

2020-11-12 15:36 UTC, closed without merging

2020-11-12 20:45 UTC, WojtekMs commented on homework/shared_ptr/tests/shared_tests.cpp
> +}
That's true :D

2020-11-16 15:35 UTC, ziobron commented
{
"requirement_ids": [1119, 1119, 1119]
}