Homework - Unique Pointer
coders-school/memory-management pull request #43
Opened 2020-10-12 19:34 UTC by DamiXioR

2020-10-12 21:56 UTC, jakjan95 reviewed
Code looks good, just one comment from me :)

2020-10-12 21:56 UTC, jakjan95 commented on homework/unique_ptr/UniquePointer.hpp
> +    void reset(T* pointer);
here you can put default argument T* pointer = nullptr

2020-10-13 00:52 UTC, MaciejSalamonski approved these changes
You should add workflow file witlhvalgrind to prove that there are no memory leaks

2020-10-13 21:09 UTC, J-Cieplinski commented on homework/unique_ptr/UniquePointer.hpp
> +    }
same here

2020-10-13 21:09 UTC, J-Cieplinski commented on homework/unique_ptr/UniquePointer.hpp
> +    pointer_ = pointer;
you can safely call delete on nullptr. And there is no need to assign nullptr after deleting it. You assign another pointer to it one line down

2020-10-13 21:11 UTC, J-Cieplinski commented on homework/unique_ptr/UniquePointer.hpp
> +T* UniquePointer<T>::replace()
I think you meant `release`

2020-10-14 07:17 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-10-14 07:17 UTC, WBigaj commented on homework/unique_ptr/UniquePointer.hpp
> +    void reset(T* pointer);
+1

2020-10-14 07:17 UTC, WBigaj commented on homework/unique_ptr/UniquePointer.hpp
> +    }
Like @J-Cieplinski said deleting nullptr is safe.

2020-10-14 07:17 UTC, WBigaj commented on homework/unique_ptr/main.cpp
> +    */
Why there is so much commented code in the main.

2020-10-14 14:11 UTC, ziobron requested changes
CI with valgrind or asan can prove that there are no memory leaks. Please add it and fix issues mentioned by me and others.

2020-10-14 14:11 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +        }
duplication?

2020-10-14 14:11 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +        }
duplication?

2020-10-14 14:11 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +        }
duplication as well. There is a missing test for `reset()` without argument

2020-10-14 14:11 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +        }
already covered, duplication

2020-10-14 14:11 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +}
there are duplicated tests cases, but there missing tests for moving.

2020-10-21 13:15 UTC, DamiXioR commented on homework/unique_ptr/UniquePointer.hpp
> +T* UniquePointer<T>::replace()
of course it's release instead replace :P

2020-10-21 13:20 UTC, DamiXioR commented on homework/unique_ptr/main.cpp
> +    */
deleted pointer is no nullptr pointer, I forgot about commented code

2020-10-21 13:20 UTC, DamiXioR commented on homework/unique_ptr/UniquePointer.hpp
> +    T* replace();
yes, thats true, my mistake :P

2020-10-21 13:21 UTC, DamiXioR commented on homework/unique_ptr/UniquePointer.ut.cpp
> +        }
thanks, i tried to change it

2020-10-21 16:31 UTC, DamiXioR commented
suggestions included

2020-10-22 06:14 UTC, ziobron approved these changes
Still there are duplicated testcases, but all needed cases are covered. Please keep in mind that duplication is also a problem. Less code == better code.

2020-10-22 06:14 UTC, ziobron commented on homework/unique_ptr/UniquePointer.hpp
> +}
can be joined with above reset by adding a function default parameter `T* pointer = nullptr`. Less code == better code.

2020-10-22 06:14 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +            anyPtr = std::move(ptr1);
```suggestion
            UniquePointer<int> anyPtr{new int{someValue}};
            anyPtr = std::move(ptr1);
```

This version is better, because you may have memory leaks detected when you implementation is wrong. 
However your implementation of move assignment is correct, but with this test you are not able to detect memory leaks.

2020-10-22 06:14 UTC, ziobron commented on homework/unique_ptr/UniquePointer.ut.cpp
> +        }
the same test as in line 87

2020-10-22 06:15 UTC, ziobron commented
{ "requirement_ids": [3784] }
36 XP za implementację unique_ptra (3784)

2020-10-22 06:15 UTC, closed without merging