shared_ptr/make_shared/weak_ptr
coders-school/memory-management pull request #44
Opened 2020-10-13 17:56 UTC by J-Cieplinski

@J-Cieplinski
@majkel84

2020-10-13 22:17 UTC, MaciejSalamonski approved these changes
Very nice code ;~} 👍

2020-10-14 07:15 UTC, WBigaj approved these changes
I have checked your code and it looks great 👍

2020-10-14 16:12 UTC, WojtekMs commented on homework/shared_ptr/shared_ptr.hpp
> +    explicit shared_ptr(T* ptr);
I think you do not need explicit in the default c-tor ;)

2020-10-14 16:12 UTC, WojtekMs commented on homework/shared_ptr/shared_ptr.hpp
> +    explicit operator bool() const noexcept;
I think operator bool() should not be explicit. This way in if statement you would have to write code like:
`if(bool(ptr))`

2020-10-14 16:41 UTC, J-Cieplinski commented on homework/shared_ptr/shared_ptr.hpp
> +    explicit operator bool() const noexcept;
we don't have to

2020-10-14 16:51 UTC, WojtekMs reviewed
Good code :)
shared_ptr(const weak_ptr<T>&) would come in handy though

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr{newPtr, deleter}.swap(*this);
Nice one :)

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/control_block.hpp
> +    }
Why are you passing an empty lambda as a deleter?

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/weak_ptr.hpp
> +    weak_ptr(const shared_ptr<T>& ptr) noexcept;
I think it would be good to add explicit to c-tor with shared_ptr

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/weak_ptr.hpp
> +    return *this;
remember to check if you are not self-assigning and to decreaseWeakRefs before `counter_ = ptr.counter_`

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/weak_ptr.hpp
> +    return *this;
remember to decrease weakRefs :)

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/weak_ptr.hpp
> +    }
This code works, is very short and very smart :) However, move operations should be treated as an optimization. I think creating temporary object is not the best way to do it.

2020-10-14 16:51 UTC, WojtekMs commented on homework/shared_ptr/weak_ptr.hpp
> +    return (counter_ == nullptr || counter_->getRefs() == 0);
smart :)

2020-10-14 17:01 UTC, J-Cieplinski commented on homework/shared_ptr/control_block.hpp
> +    }
Nature of continuous_block. I don't want to delete T if sharedRefs get to 0. Nature of `if any std::weak_ptr references the control block created by std::make_shared after the lifetime of all shared owners ended, the memory occupied by T persists until all weak owners get destroyed as well,`

2020-10-14 17:04 UTC, WojtekMs commented on homework/shared_ptr/shared_ptr.hpp
> +    explicit operator bool() const noexcept;
True, I didn't know about contextual conversions. It's interesting, thanks

2020-10-22 21:08 UTC, jakjan95 approved these changes
For me everything looks good +1

2020-10-31 20:33 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +    weak_ptr(const shared_ptr<T>& ptr) noexcept;
done

2020-10-31 20:33 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +    return *this;
done

2020-10-31 20:33 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +    return *this;
done

2020-11-05 15:41 UTC, ziobron requested changes
exercises and unique_ptr should not be commited. I have checked only shared_ptr and make_shared part. Let me check weak_ptr later.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/control_block.hpp
> +        weakRefs_ = 0;
it's not needed. Zeroing memory takes additional time on destruction.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(T* ptr, std::function<void(T*)> deleter);
you can merge this constructor with above by adding a default parameter value to deleter

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    T& operator*();
```suggestion
    const T* operator->() const;
    T& operator*() const;
```

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    size_t use_count() { return counter_->getRefs(); }
```suggestion
    size_t use_count() const { return counter_->getRefs(); }
```

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +        }
```suggestion
    if (!counter_->getRefs()) {
        counter_->deleter_(ptr_);
        if (!counter_->getWeakRefs()) {
            delete counter_;
        }
```

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    if (!counter_->getRefs()) {
you may add decrementing here before any checks.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    ++*counter_;
your control block may be created by default with 1. There will be no need to increment it here and in some other places.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    counter_ = counterTmp;
you may call std::swap 2 times instead of those 6 lines.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr{newPtr, deleter}.swap(*this);
it may be unsafe. You need a test as a proof that it works correctly. What about such case:
```cpp
cs::shared_ptr<int> sh{};
int* p = new int{5};
sh.reset(p);
p = 10;
```

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +        throw std::runtime_error("Dereferencing a nullptr");
it's not a normal shared_ptr behavior. I guess that you wanted to have your own behavior here.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    if(counter_){
what about self assignment here?

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    cs::shared_ptr<int> sPtr2;
```suggestion
    cs::shared_ptr<int> sPtr2{new int{100}};
```
This may cause some memory leaks if you have bad implementation, so it is better to use it in tests. The same in other places and tests like testMoveAssignment.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    ASSERT_EQ(uPtr2->at(1), 'l');
```suggestion
    ASSERT_EQ(uPtr2->at(0), testString[0]);
    ASSERT_EQ(uPtr2->at(1), testString[1]);
```
Write code in such way that will require you less changes in future. With my bersion it will work even if you change the content of testString.

2020-11-05 15:41 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +}
very good tests!

2020-11-05 16:30 UTC, J-Cieplinski commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(T* ptr, std::function<void(T*)> deleter);
I tried, it would not work. If I recall correctly it was first checking for matching function, and in that case both `shared_ptr()`(which was deleted) and overloaded `T* ptr = nullptr` were detected and there was compilation error. I've read that first the compiler tries to use correct overloaded function and then checks for deleted functions etc.

2020-11-05 19:45 UTC, ziobron requested changes
Review finished.

2020-11-05 19:45 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +}
in fact you can merge those 2 tests. Their bodies are almost the same.

2020-11-05 19:45 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    cs::weak_ptr<int> wPtr = sPtr;
it's not copy assignment. It will take place if your wPtr was already pointing to something else.

2020-11-05 19:45 UTC, ziobron commented on homework/shared_ptr/test.cpp
> +    auto wPtr2 = std::move(wPtr);
it's move constructor. The same as for copy - wPtr2 needs to be initialized before assignment to call move assignment operator.

2020-11-05 19:45 UTC, ziobron commented on homework/shared_ptr/weak_ptr.hpp
> +    }
```suggestion
    if (this != &ptr) {
        if(counter_) {
            counter_->decreaseWeakRefs();
            checkAndDeletePointers();
        }
        ptr_ = ptr.ptr_;
        counter_ = ptr.counter_;
        counter_->increaseWeakRefs();
    }
```

2020-11-05 19:45 UTC, ziobron commented on homework/shared_ptr/weak_ptr.hpp
> +        previousOwner.counter_ = nullptr;
I can smell a possible memory leak here. You have not tested this operator. In test move constructor is called.
Especially check it with a case when we have 2 or more weak_ptrs (pointing to the same thing) and we want to move one of them to something else using this operator. Check it please against such a scenario.

2020-11-05 20:19 UTC, majkel84 commented on homework/shared_ptr/test.cpp
> +}
done

2020-11-05 20:44 UTC, majkel84 commented on homework/shared_ptr/test.cpp
> +    cs::weak_ptr<int> wPtr = sPtr;
done

2020-11-05 20:52 UTC, majkel84 commented on homework/shared_ptr/test.cpp
> +    auto wPtr2 = std::move(wPtr);
done

2020-11-05 20:54 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +    }
done

2020-11-05 21:09 UTC, majkel84 commented on homework/shared_ptr/weak_ptr.hpp
> +        previousOwner.counter_ = nullptr;
yes You right :) additional test case added.
reset() for previous owner added to operator=

2020-11-05 21:28 UTC, majkel84 commented on homework/shared_ptr/control_block.hpp
> +        weakRefs_ = 0;
done

2020-11-05 21:28 UTC, majkel84 commented on homework/shared_ptr/shared_ptr.hpp
> +    T& operator*();
done

2020-11-05 21:28 UTC, majkel84 commented on homework/shared_ptr/shared_ptr.hpp
> +    size_t use_count() { return counter_->getRefs(); }
done

2020-11-05 21:29 UTC, majkel84 commented on homework/shared_ptr/shared_ptr.hpp
> +        }
done

2020-11-05 21:31 UTC, majkel84 commented on homework/shared_ptr/shared_ptr.hpp
> +    if(counter_){
done

2020-11-05 21:33 UTC, majkel84 commented on homework/shared_ptr/test.cpp
> +    cs::shared_ptr<int> sPtr2;
done
we ave good implementation - no memory leaks here :)

2020-11-05 21:37 UTC, majkel84 commented on homework/shared_ptr/test.cpp
> +    ASSERT_EQ(uPtr2->at(1), 'l');
done

2020-11-12 22:49 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(T* ptr, std::function<void(T*)> deleter);
Yes, but do not give default value for ptr. Give it to deleter only

2020-11-13 13:58 UTC, ziobron approved these changes

2020-11-13 14:00 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796], "users": ["J-Cieplinski", "majkel84"] }

2020-11-13 14:00 UTC, closed without merging

2020-11-16 15:35 UTC, ziobron commented
{
"requirement_ids": [1636],
"users": ["J-Cieplinski", "majkel84"]
}