UniquePointer Implementation
coders-school/memory-management pull request #45
Opened 2020-10-21 20:27 UTC by kontrybutor

2020-10-22 06:30 UTC, ziobron requested changes
Missing unit tests and CI with valgrind / asan.

2020-10-22 06:30 UTC, ziobron commented on homework/unique_ptr/uniquePtr.hpp
> +        if (m_data) {
if not needed. delete on nullptr is safe.

2020-10-22 06:30 UTC, ziobron commented on homework/unique_ptr/uniquePtr.hpp
> +        return result;
```suggestion
        T* result = nullptr;
        std::swap(result, m_data);
        return result;
```

2020-10-22 06:30 UTC, ziobron commented on homework/unique_ptr/uniquePtr.hpp
> +    }
```suggestion
    void reset(T* data = nullptr) noexcept
    {
        delete m_data;
        m_data = data;
    }
```

2020-10-22 07:12 UTC, MaciejSalamonski approved these changes

2020-10-22 07:12 UTC, MaciejSalamonski commented on homework/unique_ptr/uniquePtr.hpp
> +    T& operator*() const { return m_data; };
I suggest you to throw an exception there

2020-10-22 07:34 UTC, WBigaj reviewed
I have checked your code and have one question.

2020-10-22 07:34 UTC, WBigaj commented on homework/unique_ptr/uniquePtr.hpp
> +        return *this;
You are returning *this anyway. Can't you refactor it to not repeat yourself.

2020-11-03 12:20 UTC, ziobron requested changes
Missing tests and build system

2020-11-03 12:20 UTC, ziobron commented on .github/workflows/manual.yml
> +        cmake ..
missing CMakeLists.txt to run cmake

2020-11-14 22:41 UTC, closed without merging