Homework make unique
coders-school/memory-management pull request #46
Opened 2020-10-27 17:27 UTC by DamiXioR

2020-10-27 17:41 UTC, MaciejSalamonski approved these changes
I think that homework make_unique should be in repo Templates

2020-10-28 17:32 UTC, WBigaj reviewed
I have checked your code and I think you can skip few ifs,because deleting nullptr is safe.

2020-10-28 17:32 UTC, WBigaj commented on homework/unique_ptr/UniquePointer.hpp
> +    }
I think this if is uncessary,because deleting nullptr is safe.

2020-10-28 17:32 UTC, WBigaj commented on homework/unique_ptr/UniquePointer.hpp
> +    }
I think this if is uncessary,because deleting nullptr is safe.

2020-11-05 08:27 UTC, jakjan95 reviewed
I think that for make_unique you should make PR to templates repo :)

2020-11-05 20:15 UTC, ziobron requested changes
Generally, you test unique_ptr here, not make_unique. You have covered scenario that assures that your implementation uses variadic templates (can pass any number of parameters to make_unique).
I want to see scenarios for detecting if perfect forwarding was used, eg. if the proper move or copy constructor was called.
There should also be a scenario for creating arrays with make_unique.

2020-11-05 20:15 UTC, ziobron commented on homework/unique_ptr/UniquePointer.hpp
> +}
what about arrays? This version cannot handle arrays properly.

2020-11-05 20:15 UTC, ziobron commented on homework/unique_ptr/MakeUnique.ut.cpp
> +            THEN("Should create unique pointer using move constructor and free memory")
ok, but how to check that move constructor was called?

2020-11-05 20:15 UTC, ziobron commented on homework/unique_ptr/MakeUnique.ut.cpp
> +                REQUIRE((*uniquePointerForMoreArguments).second == firstNumber);
it does not test make_unique. It is unique_ptr test. You can remove it.

2020-11-06 17:29 UTC, DamiXioR commented on homework/unique_ptr/UniquePointer.hpp
> +}
i changed all implementation, now it works with std::unique_ptr, i had problems with my own UniquePointer implementation, so i cant handle arrays

2020-11-06 19:19 UTC, DamiXioR commented
i change UniquePointer implementation and now it works with arrays, make unique should works too

2020-11-11 20:59 UTC, ziobron requested changes

2020-11-11 20:59 UTC, ziobron commented on homework/unique_ptr/UniquePointer.hpp
> +class UniquePointer<T[]> {
no need for such class duplication. You can only provide a proper deleter to casual unique pointer implementation. That's the only difference. Just make your delete functions replaceable.
1. Extract all delete usages into deleter function.
2. Add a uniqe_ptr constructor that also takes a deleter. Default deleter is just calling delete.
3. Use it in make_unique for arrays

2020-11-11 20:59 UTC, ziobron commented on homework/unique_ptr/MakeUnique.ut.cpp
>      }
please add tests for lvalue and rvalue check. Proper functions/constructors should be used on move/copy operations. If you don't know what is it about take a look into other's PR in templates repo.

2020-11-12 18:40 UTC, DamiXioR commented on homework/unique_ptr/UniquePointer.hpp
> +class UniquePointer<T[]> {
i left it with specialization, it was to hard for me to do it with one class, i added deleters

2020-11-13 14:10 UTC, ziobron approved these changes
I really don't like this duplication but let it be ;)

2020-11-13 14:10 UTC, ziobron commented on homework/unique_ptr/UniquePointer.hpp
> +    void reset(T* pointer, std::function<void(T*)> deleter = defaultBlockDeleter<T>);
no need to have both functions. Do sth like this:
```suggestion
    void reset(T* pointer = nullptr, std::function<void(T*)> deleter = defaultBlockDeleter<T>);
```

2020-11-13 14:11 UTC, ziobron requested changes
Aaa and tests for rvalue and lvalue forwarding are still missing! Please add them

2020-11-14 22:44 UTC, ziobron approved these changes
👍

2020-11-14 22:46 UTC, ziobron commented
{ "requirement_ids": [4443], "points": [40] }
40 XP za Szablony #1 – make_unique (4443)

2020-11-14 22:46 UTC, closed without merging