Homework shared_ptr, weak_ptr, make_shared
coders-school/memory-management pull request #47
Opened 2020-10-29 20:10 UTC by Kuba-Wi

2020-10-29 23:52 UTC, MaciejSalamonski approved these changes
Imo it look ok +1

2020-10-30 19:37 UTC, WBigaj approved these changes
I have checked your code and it looks good 👍

2020-11-07 11:01 UTC, ziobron requested changes

2020-11-07 11:01 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    ASSERT_EQ(weak_something.use_count(), numberOfUseCount);
you may also show that before copy use_count was 0. The same in move in a test above.

2020-11-07 11:01 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +  weakSomething.reset();
you should also check if after reset we have use_count == 0 or pointer is expired and it is not after reassignment.

2020-11-07 13:31 UTC, Kuba-Wi commented on homework/shared_ptr/weak_ptr.hpp
> +        cb_->setDeleter([&]() { delete ptr_; });
It is needed because otherwise deleter will call delete on old pointer that doesn't point on anything.

2020-11-07 13:34 UTC, Kuba-Wi commented on homework/shared_ptr/weak_ptr.hpp
> +        cb_->setDeleter([&]() { delete ptr_; });
It is needed because otherwise deleter will call delete on old pointer that doesn't point on anything.

2020-11-07 13:35 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr.hpp
> +    cb_->setDeleter([&]() { delete ptr_; });
It is needed because otherwise deleter will call delete on old pointer that doesn't point on anything.

2020-11-07 13:35 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr.hpp
> +        cb_->setDeleter([&]() { delete ptr_; });
It is needed because otherwise deleter will call delete on old pointer that doesn't point on anything.

2020-11-10 22:27 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr.hpp
> +    long use_count() const { return static_cast<long>(cb_->getShared()); }
Declaration on cppreference:
long use_count() const noexcept;

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/control_block.hpp
> +    ControlBlock() = default;
with only default constructor, you don't have a way to provide a custom deleter.

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/control_block.hpp
> +    const T& getObject() const { return object_; }
why not return T*? you cannot modify underlying object with const&. Previous version was ok.

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(T* ptr = nullptr) : ptr_(ptr), cb_(new ControlBlock<T>) {}
passing a deleter here was really fine. Bring back the previous version :D

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/control_block.hpp
>      std::atomic<size_t>& getWeak() { return weak_refs; }
return size_t not atomic<size_t>

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(BlockAndData<T>* cb) : cb_(cb) { ptr_ = new T{cb->getObject()}; };
no, you have 2 objects right now. In a control block and a newly created on the heap.

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    cb_ = new ControlBlock<T>;
and decrement shared refs if ptr_ is nullptr. Add a proper test for it. use_count should return 0 for nulltprs.

2020-11-13 14:32 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    long use_count() const { return static_cast<long>(cb_->getShared()); }
ok

2020-11-13 14:34 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    cb_->setDeleter([&]() { delete ptr_; });
No. it will be called on the pointer that was set during the construction of the control block, and it was exactly ptr.ptr_, which you have just copied to ptr_. So it should be ok.

2020-11-13 15:05 UTC, ziobron requested changes

2020-11-13 15:05 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    ++numberOfUseCount;
I really don't like the incrementation here and in a few other places. It tells me that the first the other use_count has something in common. In fact, they are independent, because they use another share_ptr. I opt for having two separated numberOfUseCount variables with 0 and 1 values here.

2020-11-13 15:05 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
>      cs::weak_ptr<Something> weak_ptr;
please initialize this weak_ptr with another shared_ptr before move. With such empty weak_ptr, some resources may not leak.

2020-11-13 15:05 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
>      cs::weak_ptr<Something> weak_ptr;
please initialize this weak_ptr with another shared_ptr before copy. With such empty weak_ptr, some resources may not leak.

2020-11-13 15:05 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    weakSomething.reset();
you can also check that this reset does not change s_ptr and everything is okay with it. Also, check use_count before reset.

2020-11-13 20:12 UTC, Kuba-Wi commented on homework/shared_ptr/control_block.hpp
> +    const T& getObject() const { return object_; }
I don't want to change so it's const&. It doesn't return pointer because object_ is allocated on stack and in place where I call this method I allocate memory via new. Ok I could return pointer and then dereference it to call new, but it would be pointless.

2020-11-13 20:13 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(T* ptr = nullptr) : ptr_(ptr), cb_(new ControlBlock<T>) {}
Previous deleter was faulty.

2020-11-13 20:16 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(BlockAndData<T>* cb) : cb_(cb) { ptr_ = new T{cb->getObject()}; };
But one is created on the stack.

2020-11-13 20:43 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr-ut.cpp
>      ASSERT_EQ(ptr.use_count(), numberOfUseCount);
I checked for std::shared_ptr and use_count before reset was 2.

2020-11-13 22:04 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr.hpp
> +    cb_ = new ControlBlock<T>;
When I copy shared_ptr that points on nullptr then delete on cb_ is called twice. So more convenient is to leave it as it is and add condition in use_count().

2020-11-13 22:35 UTC, Kuba-Wi commented on homework/shared_ptr/shared_ptr-ut.cpp
>  }
added tests for copying and moving

2020-11-14 12:30 UTC, kuchichan commented on homework/shared_ptr/shared_ptr-ut.cpp
>  }
Also, additional test for `tuple<int, int, int>` 3 parameter and empty string (0 parameter) added.

2020-11-14 22:50 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
>      ASSERT_EQ(ptr.use_count(), numberOfUseCount);
that's true. But my comment was about use_count after reset, not before.
ptr.use_count = 0
ptr_doing_nothing.use_count = 1

2020-11-14 22:57 UTC, ziobron approved these changes
Good job 👍

2020-11-14 22:58 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{
  "requirement_ids": [3794, 3795, 3796],
   "users": ["kuchichan", "Kuba-Wi"]
}

2020-11-14 22:58 UTC, closed without merging

2020-11-16 15:36 UTC, ziobron commented
{
"requirement_ids": [1636],
"users": ["kuchichan", "Kuba-Wi"]
}