Homework shared_ptr, weak_ptr, make_shared
coders-school/memory-management pull request #48
Opened 2020-10-31 17:57 UTC by mateusz-talma

2020-10-31 20:00 UTC, MaciejSalamonski approved these changes
Good job :) I have only one question

2020-10-31 20:00 UTC, MaciejSalamonski commented on homework/shared_ptr/WeakPtr.hpp
> +    return 0l;
What is 0l? It is a long number?

2020-11-01 11:37 UTC, mateusz-talma commented on homework/shared_ptr/WeakPtr.hpp
> +    return 0l;
0L is a long integer number with all bits set to zero. In this case, 0L is the same as 0 (0 will be cast to long)

2020-11-01 12:35 UTC, MaciejSalamonski commented on homework/shared_ptr/WeakPtr.hpp
> +    return 0l;
Thanks ;~}

2020-11-02 08:44 UTC, WBigaj reviewed
I have checked your code and left my feedback.

2020-11-02 08:44 UTC, WBigaj commented on exercises/FileOperations.cpp
> +>>>>>>> 9addd5891723a1d66eecbe4dfdc328007e9895c7
What are those merging leftovers?

2020-11-02 08:44 UTC, WBigaj commented on exercises/FileOperations.cpp
> +    FileHandler fh("../ResourceD.cpp");
I think filepath can be constexpr variable.

2020-11-02 08:44 UTC, WBigaj commented on homework/shared_ptr/SharedPtr.hpp
> +                         std::function<void(T*)> deleter /* = [](T* ptr = nullptr) { delete ptr; }*/) noexcept {
What are those comment in the middle of the code?

2020-11-02 08:44 UTC, WBigaj commented on exercises/FileOperations.cpp
> +>>>>>>> 9addd5891723a1d66eecbe4dfdc328007e9895c7
Another merging leftovers here.

2020-11-02 11:03 UTC, mateusz-talma commented on exercises/FileOperations.cpp
> +    FileHandler fh("../ResourceD.cpp");
This is a file from another task, but actually, it should be constexpr :)

2020-11-02 11:10 UTC, mateusz-talma commented on homework/shared_ptr/SharedPtr.hpp
> +                         std::function<void(T*)> deleter /* = [](T* ptr = nullptr) { delete ptr; }*/) noexcept {
We use this notation in my work team. This shows in the cpp file that the function argument can take its default value.
However, this solution has a disadvantage - this means duplication and will add the possibility of having the comment out of sync with the code (e.g. when we will change default value of argument in hpp file and we will not synchronize this changes in comment.

2020-11-07 12:01 UTC, ziobron requested changes
exercises should not be commited. unique_ptr should not be commited.
make_shared is not working.

2020-11-07 12:01 UTC, ziobron commented on homework/shared_ptr/WeakPtr-ut.cpp
> +
copy assignment is not tested

2020-11-13 15:36 UTC, ziobron requested changes
almost good :)

2020-11-13 15:36 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +    void setDeleter(std::function<void(T*)> del) { deleter_ = del; }
please set it only in the constructor and remove setDeleter function. We don't want to replace a deleter later. It should be bind to object during construction.

2020-11-13 15:36 UTC, ziobron commented on homework/shared_ptr/ControlBlock.hpp
> +    virtual void callDeleter() {}
isn't it better to have it pure virtual here?

2020-11-13 15:36 UTC, ziobron commented on homework/shared_ptr/WeakPtr-ut.cpp
> +    cs::WeakPtr<int> weakPtr2 = weakPtr;
copy constructor is used here. Use this form
```suggestion
    cs::WeakPtr<int> weakPtr2{some_other_shared_ptr};
    weakPtr2 = weakPtr;
```

2020-11-14 23:02 UTC, ziobron approved these changes
Well done 👍

2020-11-14 23:03 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796] }

2020-11-14 23:03 UTC, closed without merging