Homework smart ptrs - shared_ptr, weak_ptr
coders-school/memory-management pull request #49
Opened 2020-11-02 22:52 UTC by niemarcin

2020-11-02 23:18 UTC, MaciejSalamonski approved these changes
good job :+1:

2020-11-03 09:17 UTC, WBigaj approved these changes
I have checked your code and it looks good 👍

2020-11-05 08:29 UTC, jakjan95 reviewed
For me code looks good, nice usage of BDD approach in UT :)

2020-11-07 12:58 UTC, ziobron requested changes

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/exceptions.hpp
> +    }
no need to have them. Remove. what() is already implemented in a base class exactly in this way. The destructor will be virtual because the base class has a virtual destructor. If you really want you can use override on it, but it is not necessary. Less code == better code.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/control_block.hpp
> +    std::atomic_size_t sharedRefs_{0};
you may already start with 1. It will be one operation less during every creation.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    shared_ptr(T* ptr, Deleter<T> deleter) noexcept;
if you had a default value for deleter you could merge these constructors

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +        rawPtr_ = nullptr;
No need to do it. You can enter here only if you had the last shared_ptr so for sure rawPtr_ will not be used. Zeroing it cost some CPU cycles.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +            ctrl_ = nullptr;
the same here.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    ctrl_ = new control_block<T>();
move to init list

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr.hpp
> +    ctrl_ = new control_block<T>(deleter);
move to init list

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +    ASSERT_EQ(emptySharedPtr.use_count(), sharedPtrCnt);
shouldn't it be 0 for nullptr? check with std::shared_ptr behavior.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +    ++sharedPtrCnt;
maybe not increment it in when. It should be done in then, or simply compare with sharedPtrCnt + 1. I don't like the name sharedPtrCnt. Maybe `expectedSharedCount`?

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +    coders::shared_ptr<int> newShared;
please do not use the default constructor before copy/move into this object. Nothing can leak here.
```suggestion
    coders::shared_ptr<int> newShared{new int{0}};
```

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +    coders::shared_ptr<int> newShared;
please do not use the default constructor before copy/move into this object. Nothing can leak here.
```suggestion
    coders::shared_ptr<int> newShared{new int{0}};
```

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/shared_ptr-ut.cpp
> +    ASSERT_EQ(sharedPtr.get(), nullptr);
what about use_count here? compare with std::shared_ptr.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/weak_ptr.hpp
> +        ctrl_ = nullptr;
no need to set it to nullptr

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    coders::weak_ptr<int> weakPtr;
assign some other shared_ptr to this weak_ptr before assignment. Nothing can leak if weak_ptr was created with default constructor.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    coders::weak_ptr<int> anotherWeakPtr;
here as well, assign something here in a constructor before calling assignment operator.

2020-11-07 12:58 UTC, ziobron commented on homework/shared_ptr/weak_ptr-ut.cpp
> +    coders::weak_ptr<int> anotherWeakPtr;
here as well, assign something here in a constructor before calling assignment operator.

2020-11-09 22:38 UTC, niemarcin commented
@ziobron I've updated the code according to your comments. Thanks for your review! ;)

2020-11-13 15:48 UTC, ziobron approved these changes
👍

2020-11-13 15:49 UTC, ziobron commented
50 XP za implementację shared_ptra (3794)
25 XP za implementację weak_ptra (3795)
40 XP za implementację make_shared (3796)
{ "requirement_ids": [3794, 3795, 3796] }

2020-11-13 15:49 UTC, closed without merging