Homework UniquePtr implementation
coders-school/memory-management pull request #50
Opened 2020-11-04 19:31 UTC by Marcinati

2020-11-04 20:05 UTC, MaciejSalamonski approved these changes
Good job :)

2020-11-04 20:05 UTC, MaciejSalamonski commented on homework/unique_ptr/UniquePtr.hpp
> +        throw InvalidDereference("You can't dereference a null pointer.");
+1

2020-11-04 20:11 UTC, MaciejSalamonski approved these changes
I don't have any comments :) good job

2020-11-05 08:25 UTC, jakjan95 reviewed
For me code looks good, i didn't find any magic values in tests, I left some advices for improving code :)

2020-11-05 08:25 UTC, jakjan95 commented on homework/unique_ptr/UniquePtr.hpp
> +        throw InvalidDereference("You can't dereference a null pointer.");
here I would rather put condition !rawPtr_ for throwing exception, and for function by default returning *rawPtr_

2020-11-05 08:25 UTC, jakjan95 commented on homework/unique_ptr/UniquePtr.hpp
> +}
here you can put default argument which is nullptr, to allow use just simple reset()

2020-11-05 10:16 UTC, WBigaj reviewed
I have checked your code and have nothing to add that was not mentioned by previous reviewers.

2020-11-05 20:28 UTC, ziobron requested changes

2020-11-05 20:28 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    void reset(T * newPtr);
default value would be useful
```suggestion
    void reset(T * newPtr = nullptr);
```

2020-11-05 20:28 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +    uniquePtr.reset(nullptr);
```suggestion
    uniquePtr.reset();
```
allow calling it without argument

2020-11-05 20:28 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
missing tests for moving unique_ptrs

2020-11-06 18:02 UTC, Marcinati commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
two tests added

2020-11-07 09:42 UTC, ziobron requested changes

2020-11-07 09:42 UTC, ziobron commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
there is still no test for the move assignment operator.

2020-11-12 17:58 UTC, Marcinati commented on homework/unique_ptr/UniquePtr-ut.cpp
> +}
sorry for misunderstanding :)

2020-11-12 22:44 UTC, ziobron approved these changes

2020-11-13 14:01 UTC, ziobron commented
36 XP za implementację unique_ptra (3784)
{ "requirement_ids": [3784], "points": [36] }

2020-11-13 14:01 UTC, closed without merging