Translation
coders-school/memory-management pull request #7
Opened 2020-08-30 12:07 UTC by Penthurion

2020-08-30 13:38 UTC, MrMijagi reviewed
CR zrobione, dwie rzeczy bodajże zasugerowałem + kilka literówek 🙂

2020-08-30 13:38 UTC, MrMijagi commented on module2/07_best_practices.pl.md
> +Kolejność oceny operandów prawie wszystkich operatorów C ++ (w tym kolejność
```suggestion
Kolejność oceny operandów prawie wszystkich operatorów C++ (w tym kolejność
```

2020-08-30 13:38 UTC, MrMijagi commented on module2/08_implementation_details.pl.md
> +  * <!-- .element: class="fragment fade-in" --> liczący słabe wskazówki
```suggestion
  * <!-- .element: class="fragment fade-in" --> liczący wspólne wskaźniki (<code>shared-refs</code>)
  * <!-- .element: class="fragment fade-in" --> liczący słabe wskazówki (<code>weak-refs</code>)
```

2020-08-30 13:38 UTC, MrMijagi commented on module2/08_implementation_details.pl.md
> +  * <!-- .element: class="fragment fade-in" --> liczący słabe wskazówki
Tylko podać nazwy, żeby było jasne że o nich mowa, bo są niżej użyte.

2020-08-30 13:38 UTC, MrMijagi commented on module2/09_efficiency.pl.md
> +  * <!-- .element: class="fragment fade-in" --> valgrind (allocations count)
```suggestion
  * <!-- .element: class="fragment fade-in" --> time (czas)
  * <!-- .element: class="fragment fade-in" --> htop (użyta pamięć)
  * <!-- .element: class="fragment fade-in" --> valgrind (liczba alokacji) 
```

2020-08-30 13:38 UTC, MrMijagi commented on module2/09_efficiency.pl.md
> +  <!-- czy zamienić słowa w nawiasach na polskie odpowiedniki tj: time (rzeczywisty), htop (pamięć), valgrind (liczba alokacji); patrząc na ten fragment mam dylemat bo z jednej strony da się, z drugi
W slajdzie niżej w tabelce te nazwy są przetłumaczone, dlatego podaję moją propozycję przetłumaczenia 🙂

2020-08-30 13:38 UTC, MrMijagi commented on module3/03_cost.pl.md
> +* [Exceptional flow](https://quick-bench.com/q/sKFj6SN0Jxx2l-beKR7JNNGh-uQ)
Tu chyba Ci uciekło, chyba że jest inny powód którego nie widzę 🙂.

2020-09-01 20:49 UTC, ziobron requested changes
Dużo tego. Sprawdziłem tylko intro i module1. W miarę możliwości przejrzyj to jeszcze module2 i 3 pod kątem uwag które do tej pory zgłosiłem.

2020-09-01 20:49 UTC, ziobron commented on README.md
> +### [Alokacja stosu](module1/03_stack_allocation.pl.md)
```suggestion
### [Alokacja na stosie](module1/03_stack_allocation.pl.md)
```

2020-09-01 20:49 UTC, ziobron commented on README.md
> +### [Alokacja sterty](module1/05_heap_allocation.pl.md)
```suggestion
### [Alokacja na stercie](module1/05_heap_allocation.pl.md)
```

2020-09-01 20:49 UTC, ziobron commented on README.md
> +### [Nowe wyrażenie i operator `new`](module1/06_new_expression.pl.md)
```suggestion
### [Wyrażenie `new` i `operator new`](module1/06_new_expression.pl.md)
```

2020-09-01 20:49 UTC, ziobron commented on README.md
> +### [Wykrywanie uszkodzeń pamięci](module1/11_memory_corruption.pl.md)
```suggestion
### [Wykrywanie problemów z pamięcią](module1/11_memory_corruption.pl.md)
```

2020-09-01 20:49 UTC, ziobron commented on README.md
> +### [New expression and operator `new`](module1/06_new_expression.en.md)
```suggestion
### [`new` expression and `operator new`](module1/06_new_expression.en.md)
```

2020-09-01 20:49 UTC, ziobron commented on intro/02_about_lukasz.pl.md
> +* Team leader i Trener w Nokia
```suggestion
* Team leader i Trener w Nokii
```

2020-09-01 20:49 UTC, ziobron commented on intro/02_about_lukasz.pl.md
> +* Code Reviewer w Nokia
```suggestion
* Scrum Master w Nokii i Credit Suisse
* Code Reviewer w Nokii
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                    * <!-- .element: class="fragment fade-in" --> oczekiwania (1h)
```suggestion
                    * <!-- .element: class="fragment fade-in" --> wyjątki (1h)
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                        1. Zwalnianie pamięci przydzielonej stercie
```suggestion
                        1. Zwalnianie pamięci zaalokowanej na stercie
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                        1. <!-- .element: class="fragment highlight-red" --> Zwalnianie tylko części przydzielonej pamięci
```suggestion
                        1. <!-- .element: class="fragment highlight-red" --> Zwalnianie pamięci zaalokowanej na stercie
                        1. <!-- .element: class="fragment highlight-green" --> Zwalnianie pamięci zaalokowanej na stosie
                        1. <!-- .element: class="fragment highlight-red" --> Zwalnianie tylko części zaalokowanej pamięci
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                        1. Zwalnianie tylko części przydzielonej pamięci
```suggestion
                        1. Zwalnianie tylko części zaalokowanej pamięci
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                        1. <!-- .element: class="fragment highlight-green" --> Nie można ponownie przypisać odwołania
```suggestion
                        1. <!-- .element: class="fragment highlight-green" --> Referencja działa jak stały wskaźnik
                        1. <!-- .element: class="fragment highlight-red" --> Referencja działa jak wskaźnik do stałej
                        1. <!-- .element: class="fragment highlight-green" --> Nie można ponownie przypisać referencji
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                    * Zaimplementuj własną funkcję shared_ptr i make_shared. Wyślij mi repozytorium, aby przejrzeć kod.
```suggestion
                    * Zaimplementuj własnego `shared_ptr` i funkcję `make_shared`. Wyślij mi repozytorium, abym mógł przejrzeć kod.
```

2020-09-01 20:49 UTC, ziobron commented on intro/index.pl.html
> +                    * Przekształć listę z List.cpp w listę podwójnie połączoną. Uważaj na cykle :)
```suggestion
                    * Przekształć listę z List.cpp w listę dwukierunkową. Uważaj na cykle :)
```

2020-09-01 20:49 UTC, ziobron commented on module1/01_memory_map.pl.md
> +* <!-- .element: class="fragment fade-in" --> stos - stos wywołań, który przechowuje adresy zwrotne, zmienne lokalne, dane tymczasowe
```suggestion
* <!-- .element: class="fragment fade-in" --> text - instrukcje maszyny
* <!-- .element: class="fragment fade-in" --> data - zainicjowane dane statyczne i globalne
* <!-- .element: class="fragment fade-in" --> bss - niezainicjowane dane statyczne
* <!-- .element: class="fragment fade-in" --> heap - sterta, pamięć przydzielana dynamicznie
* <!-- .element: class="fragment fade-in" --> stack - stos wywołań, który przechowuje adresy zwrotne, zmienne lokalne, dane tymczasowe
```

2020-09-01 20:49 UTC, ziobron commented on module1/03_stack_allocation.pl.md
> +## Alokacja stosu
```suggestion
## Alokacja na stosie
```

2020-09-01 20:49 UTC, ziobron commented on module1/03_stack_allocation.pl.md
> +* <!-- .element: class="fragment fade-in" --> Automatyczne cofanie przydziału, gdy poza zakresem
```suggestion
* <!-- .element: class="fragment fade-in" --> Automatyczne zwalnianie pamięci po wyjściu z zakresu
```

2020-09-01 20:49 UTC, ziobron commented on module1/05_heap_allocation.pl.md
> +## Alokacja sterty
```suggestion
## Alokacja na stercie
```

2020-09-01 20:49 UTC, ziobron commented on module1/05_heap_allocation.pl.md
> +Alokacja sterty składa się z kilku kroków:
```suggestion
Alokacja na stercie składa się z kilku kroków:
```

2020-09-01 20:49 UTC, ziobron commented on module1/05_heap_allocation.pl.md
> +* <!-- .element: class="fragment fade-in" --> wywołanie konstruktora <code>T</code> na przydzieloną pamięć
```suggestion
* <!-- .element: class="fragment fade-in" --> wywołanie konstruktora <code>T</code> na przydzielonej pamięci
```

2020-09-01 20:49 UTC, ziobron commented on module1/05_heap_allocation.pl.md
> +* <!-- .element: class="fragment fade-in" --> ręczne cofnięcie przydziału przy użyciu operatora <code>delete</code>
```suggestion
* <!-- .element: class="fragment fade-in" --> ręczne zwolnienie pamięci przy użyciu operatora <code>delete</code>
```

2020-09-01 20:49 UTC, ziobron commented on module1/06_new_expression.pl.md
> +## Nowe wyrażenie i operator `new`
```suggestion
## Wyrażenie `new` i `operator new`
```

2020-09-01 20:49 UTC, ziobron commented on module1/06_new_expression.pl.md
> +* <!-- .element: class="fragment fade-in" --> wywołanie konstruktora <code>T</code> na przydzieloną pamięć
```suggestion
* <!-- .element: class="fragment fade-in" --> wywołanie konstruktora <code>T</code> na przydzielonej pamięci
```

2020-09-01 20:49 UTC, ziobron commented on module1/06_new_expression.pl.md
> +// kilka innych wersji na https://en.cppreference.com/w/cpp/memory/new/operator_new
komentarzy w kodzie nie tłumaczcie

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +Wskaźnik wskazujący na coś, co jest nieprawidłowe
```suggestion
Wskaźnik wskazujący na wcześniej zwolnioną pamięć
```

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +Dzieje się tak, gdy wiszący wskaźnik zostanie usunięty
```suggestion
Dzieje się tak, gdy wołamy delete na wiszącym wskaźniku.
```

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +### Wyłuskiwanie wskaźnika zerowego
```suggestion
### Wyłuskiwanie `nullptr`
```

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +### Zwalnianie bloków przydzielonych na stosie
```suggestion
### Zwalnianie bloków pamięci zaalokowanych na stosie
```

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +### Zwalnianie części bloku dynamicznego
```suggestion
### Zwalnianie części bloku zaalokowanego dynamicznie
```

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +* <!-- .element: class="fragment fade-in" --> zwolnienie części bloku dynamicznego
te nazwy do poprawki zgodnie s powyższymi sugestiami

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +Wszystkie problemy z alokacją powodują Niezdefiniowane Zachowanie.
```suggestion
Wszystkie problemy z alokacją powodują UB - Undefined Behavior (Niezdefiniowane Zachowanie).
```

2020-09-01 20:49 UTC, ziobron commented on module1/08_allocation_problems.pl.md
> +Problemy te można rozwiązać za pomocą ASAN (Address Sanitizer) lub Valgrind.
```suggestion
Problemy te można wykryć za pomocą ASAN (Address Sanitizer) lub Valgrind.
```

2020-09-01 20:49 UTC, ziobron commented on module1/09_simple_question.pl.md
> +Ile jest tutaj możliwych ścieżek egzekucji?
```suggestion
Ile jest tutaj możliwych ścieżek wykonania programu?
```

2020-09-01 20:49 UTC, ziobron commented on module1/09_simple_question.pl.md
> +* <!-- .element: class="fragment fade-in" --> Wyjątki są powodem
```suggestion
* <!-- .element: class="fragment fade-in" --> Powodem są wyjątki
```

2020-09-01 20:49 UTC, ziobron commented on module1/10_raii.pl.md
> +  * <!-- .element: class="fragment fade-in" --> wydany w destruktorze
```suggestion
  * <!-- .element: class="fragment fade-in" --> każdy zasób posiada klasę nim zarządzającą
  * <!-- .element: class="fragment fade-in" --> pozyskanie zasobu w konstruktorze
  * <!-- .element: class="fragment fade-in" --> zwolnienie zasobu w destruktorze
```

2020-09-01 20:49 UTC, ziobron commented on module1/10_raii.pl.md
> +  * <!-- .element: class="fragment fade-in" --> przewidywalne czasy wydania
```suggestion
  * <!-- .element: class="fragment fade-in" --> przewidywalne czasy zwalniania zasobu
```

2020-09-01 20:49 UTC, ziobron commented on module1/11_memory_corruption.pl.md
> +## Wykrywanie uszkodzeń pamięci
```suggestion
## Wykrywanie problemów pamięci
```

2020-09-01 20:49 UTC, ziobron commented on module1/11_memory_corruption.pl.md
> +  * <!-- .element: class="fragment fade-in" --> uruchomić binarkę pod valgrind:
```suggestion
  * <!-- .element: class="fragment fade-in" --> uruchom binarkę pod valgrindem:
```

2020-09-01 20:49 UTC, ziobron commented on module1/11_memory_corruption.pl.md
> +  * <!-- .element: class="fragment fade-in" --> użyj dodatkowych kontroli:
```suggestion
  * <!-- .element: class="fragment fade-in" --> dodatkowe sprawdzenia:
```

2020-09-01 20:49 UTC, ziobron commented on module1/11_memory_corruption.pl.md
> +Oba sposoby nie działają w systemie Windows 😕
```suggestion
Oba narzędzia nie działają w systemie Windows 😕
```

2020-09-01 20:49 UTC, ziobron commented on module1/index.pl.html
> +                      * <!-- .element: class="fragment fade-in" --> nowe wyrażenie i operator <code>new</code>
```suggestion
                      * <!-- .element: class="fragment fade-in" --> alokacja na stosie
                      * <!-- .element: class="fragment fade-in" --> alokacja na stercie
                      * <!-- .element: class="fragment fade-in" --> wyrażenie <code>new</code> i <code>operator new</code>
```

2020-09-01 20:49 UTC, ziobron commented on module1/index.pl.html
> +                      * <!-- .element: class="fragment fade-in" --> problemy z alokacją dynamiczną RAII
```suggestion
                      * <!-- .element: class="fragment fade-in" --> problemy z alokacją dynamiczną
```

2020-09-01 20:49 UTC, ziobron commented on module1/index.pl.html
> +                    * <!-- .element: class="fragment fade-in" --> Wykrywanie uszkodzeń pamięci
```suggestion
                    * <!-- .element: class="fragment fade-in" --> Wykrywanie problemów z pamięcią
```

2020-09-08 22:40 UTC, ziobron reviewed
Moduł 1 i intro approved 👍 
Reszta później. Pozamieniaj "surowy wskaźnik" na "zwykły wskaźnik"

2020-09-08 22:40 UTC, ziobron commented on module2/02_unique_ptr.pl.md
> +### użycie `std::unique_ptr<>`
```suggestion
### Użycie `std::unique_ptr<>`
```

2020-09-08 22:40 UTC, ziobron commented on module2/02_unique_ptr.pl.md
> +### użycie `std::unique_ptr<>`
```suggestion
### Użycie `std::unique_ptr<>`
```

2020-09-08 22:40 UTC, ziobron commented on module2/02_unique_ptr.pl.md
> +#### Współpraca `std::unique_ptr<>` z surowymi wskaźnikami
```suggestion
#### Współpraca `std::unique_ptr<>` ze zwykłymi wskaźnikami
```

2020-09-08 22:40 UTC, ziobron commented
Byłoby wygodniej gdyby PR były podzielone na moduły :)

2020-09-09 17:16 UTC, WBigaj reviewed
Few suggestions from me.

2020-09-09 17:16 UTC, WBigaj commented on module2/09_efficiency.pl.md
> +        delete p;
```suggestion
    for (auto p: v) {
        delete p;
    }
```

2020-09-09 17:16 UTC, WBigaj commented on module2/04_weak_ptr.pl.md
> +}
```suggestion
    if (p) {
        std::cout << p->value << '\n';
    } else {
        std::cout << "Expired\n";
    }
}
```

2020-09-11 22:11 UTC, ziobron requested changes
Moduł 2 sprawdzony, poprawki zasugerowane.

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +  * <!-- .element: class="fragment fade-in" --> usuwa liczniki odwołań, gdy <code>shared-refs == 0</code> i <code>weak-refs == 0</code>
```suggestion
* <!-- .element: class="fragment fade-in" --> Zawiera wskaźnik do obiektu
* <!-- .element: class="fragment fade-in" --> Zawiera 2 liczniki odwołań:
  * <!-- .element: class="fragment fade-in" --> zliczający <code>shared_ptr</code>y (<code>shared-refs</code>)
  * <!-- .element: class="fragment fade-in" --> zliczający <code>weak_ptr</code>y (<code>weak-refs</code>)
* <!-- .element: class="fragment fade-in" --> Destruktor:
  * <!-- .element: class="fragment fade-in" --> dekrementuje <code>weak-refs</code>
  * <!-- .element: class="fragment fade-in" --> usuwa liczniki odwołań, gdy <code>shared-refs == 0</code> i <code>weak-refs == 0</code>
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +  * <!-- .element: class="fragment fade-in" --> kopiowanie wskaźników do celu
```suggestion
  * <!-- .element: class="fragment fade-in" --> kopiowanie wskaźników do docelowego <code>weak_ptr</code>a
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +  * <!-- .element: class="fragment fade-in" --> Ustawianie wskaźników źródłowych na <code>nullptr</code>
```suggestion
  * <!-- .element: class="fragment fade-in" --> kopiowanie wskaźników do docelowego <code>weak_ptr</code>a
  * <!-- .element: class="fragment fade-in" --> ustawianie wskaźników źródłowego <code>weak_ptr</code>a na <code>nullptr</code>
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +* <!-- .element: class="fragment fade-in" --> Posiadanie wspólnego wskaźnika i słabego wskaźnika
```suggestion
* <!-- .element: class="fragment fade-in" --> Gdy mamy <code>shared_ptr</code> i <code>weak_ptr</code>
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +* <!-- .element: class="fragment fade-in" --> Po usunięciu wspólnego wskaźnika
```suggestion
* <!-- .element: class="fragment fade-in" --> Gdy usuniemy ostatni <code>shared_ptr</code>...
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +## Making a `std::shared_ptr<>`
```suggestion
## Tworzenie `std::shared_ptr<>`
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +* <!-- .element: class="fragment fade-in" --> <code>std::shared_ptr&ltData&gt p{new Data};</code>
```suggestion
* <!-- .element: class="fragment fade-in" --> <code>std::shared_ptr&lt;Data&gt; p{new Data};</code>
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +* <!-- .element: class="fragment fade-in" --> <code>auto p = std::make_shared&ltData&gt();</code>
```suggestion
* <!-- .element: class="fragment fade-in" --> <code>auto p = std::make_shared&lt;Data&gt;();</code>
```

2020-09-11 22:11 UTC, ziobron commented on module2/08_implementation_details.pl.md
> +  * <!-- .element: class="fragment fade-in" --> Przyjazny dla pamięci podręcznej
```suggestion
  * <!-- .element: class="fragment fade-in" --> Tylko jedna alokacja
  * <!-- .element: class="fragment fade-in" --> Przyjazne dla pamięci podręcznej (cache)
```

2020-09-11 22:11 UTC, ziobron commented on module2/09_efficiency.pl.md
> +## Wskaźnik surowy
```suggestion
## Zwykły wskaźnik
```

2020-09-11 22:11 UTC, ziobron commented on module2/09_efficiency.pl.md
> +## Wskaźnik unikalny
```suggestion
## Wskaźnik `std::unique_ptr`
```

2020-09-11 22:11 UTC, ziobron commented on module2/09_efficiency.pl.md
> +  * <!-- .element: class="fragment fade-in" --> valgrind (liczba alokacji)
```suggestion
* <!-- .element: class="fragment fade-in" --> Pomiary wykonane za pomocą
  * <!-- .element: class="fragment fade-in" --> time (czas)
  * <!-- .element: class="fragment fade-in" --> htop (zużyta pamięć)
  * <!-- .element: class="fragment fade-in" --> valgrind (liczba alokacji) 
```

2020-09-11 22:11 UTC, ziobron commented on module2/09_efficiency.pl.md
> +## Konkluzje
```suggestion
## Podsumowanie
```

2020-09-11 22:11 UTC, ziobron commented on module2/09_efficiency.pl.md
> +  * <!-- .element: class="fragment fade-in" --> <code>std::weak_ptr</code> – łamanie cykli, można go konwertować do/z <code>std::shared_ptr</code>
```suggestion
  * <!-- .element: class="fragment fade-in" --> <code>std::weak_ptr</code> – tylko do łamania cykli, można go konwertować do/z <code>std::shared_ptr</code>
```

2020-09-11 22:11 UTC, ziobron commented on module2/09_efficiency.pl.md
> +* <!-- .element: class="fragment fade-in" --> Jeśli to możliwe, używaj odwołań zamiast wskaźników
```suggestion
* <!-- .element: class="fragment fade-in" --> Twórz inteligentne wskaźniki za pomocą <code>std::make_shared()</code> i <code>std::make_unique()</code>
* <!-- .element: class="fragment fade-in" --> Zwykły wskaźnik powinien oznaczać tylko dostęp (brak własności) 
* <!-- .element: class="fragment fade-in" --> Jeśli to możliwe, używaj referencji zamiast wskaźników
```

2020-10-16 11:20 UTC, MaciejSalamonski approved these changes

2021-09-22 07:35 UTC, ziobron commented
Wersja angielska zaadaptowana na branchu `english` :)

2021-09-22 07:35 UTC, closed without merging