Homework unique_ptr
coders-school/memory-management pull request #85
Opened 2021-11-28 11:16 UTC by lukasz-kukulka

2021-11-29 15:45 UTC, ziobron requested changes

2021-11-29 15:45 UTC, ziobron commented on homework/unique_ptr/UniquePtr.hpp
> +    void reset(T* data) {
```suggestion
    void reset(T* data = nullptr) {
```
It should allow a usage like that:
```cpp
ptr.reset();
```

Please add a proper test for this case as well.

2021-11-29 15:45 UTC, ziobron commented on homework/unique_ptr/tests.cpp
> +    ASSERT_EQ(*newObject.get(), expected);
You should also assert that `uniqueTestValueInt` is a nullptr after a move operation

2021-11-29 15:45 UTC, ziobron commented on homework/unique_ptr/tests.cpp
> +    ASSERT_NE(newObject.get(), newObjectRelease.get());
Please check that newObjectRelease is a nullptr after a release. 
Also, `release()` function returns a pointer. Check if it's a proper one.

2021-12-10 09:45 UTC, lukasz-kukulka commented on homework/unique_ptr/tests.cpp
> +    ASSERT_EQ(*newObject.get(), expected);
Done

2021-12-10 09:45 UTC, lukasz-kukulka commented on homework/unique_ptr/tests.cpp
> +    ASSERT_NE(newObject.get(), newObjectRelease.get());
Done

2022-01-21 12:12 UTC, nauka-programowania-MA approved these changes

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    }
NOEXCPET!!!!

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    UniquePtr& operator=(UniquePtr&& move) {
noexcept

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +            delete ptr_;
delete ptr is wrong here. You will never have ptr because you construct an object right now. So why call delete on nullptr :)?

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    T& operator*() const {
noexcpet

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    T& operator*() const {
Should divide into 2 methods. One const return const& and second no const return T&

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    T* operator->() const {
Same here 2 methods

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    T* operator->() const {
and noexcpet

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    T* get() const {
2 methods and noexcpet

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    T* release() {
noexcpet

2022-01-21 12:12 UTC, nauka-programowania-MA commented on homework/unique_ptr/UniquePtr.hpp
> +    void reset(T* data = nullptr) {
noexcpet

2022-01-21 12:13 UTC, closed without merging