Homework - unique_ptr
coders-school/memory-management pull request #9
Opened 2020-09-13 14:34 UTC by anraf1001

2020-09-15 11:47 UTC, jakjan95 approved these changes
Code looks very good, just add delete statement for copy assignment and it will be perfect :)

2020-09-15 13:03 UTC, anraf1001 commented
> Code looks very good, just add delete statement for copy assignment and it will be perfect :)

Copy constructor has been already deleted so copying unique_ptr isn't allowed

2020-09-19 12:54 UTC, MaciejSalamonski approved these changes
Very nice code! :}

2020-09-19 12:54 UTC, MaciejSalamonski commented on homework/unique_ptr/PtrIsNullptr.hpp
> +        : std::runtime_error("Pointer is nullptr!!!") {}
+1

2020-09-20 07:04 UTC, ziobron requested changes
An additional CI job with Valgrind would prove that there are no memory leaks. I think I have discovered one. Please check it.

2020-09-20 07:04 UTC, ziobron commented on homework/unique_ptr/unique_ptr.hpp
> +}
you have an additional exception in case of nullptr dereference. Casual unique_ptr does not check it, but it's ok for me for this implementation.

2020-09-20 20:01 UTC, ziobron approved these changes

2020-09-20 20:01 UTC, ziobron commented
{ "requirement_ids": [3784, 1119] }

2020-09-20 20:01 UTC, closed without merging